// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api.proto

package api

import (
	context "context"
	fmt "fmt"
	types "github.com/gogo/protobuf/types"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Direction int32

const (
	Direction_FORWARD  Direction = 0
	Direction_BACKWARD Direction = 1
)

var Direction_name = map[int32]string{
	0: "FORWARD",
	1: "BACKWARD",
}

var Direction_value = map[string]int32{
	"FORWARD":  0,
	"BACKWARD": 1,
}

func (x Direction) String() string {
	return proto.EnumName(Direction_name, int32(x))
}

func (Direction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{0}
}

type ChangePasswordRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{0}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ChangePasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ChangePasswordReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordReply) Reset()         { *m = ChangePasswordReply{} }
func (m *ChangePasswordReply) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordReply) ProtoMessage()    {}
func (*ChangePasswordReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{1}
}

func (m *ChangePasswordReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordReply.Unmarshal(m, b)
}
func (m *ChangePasswordReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordReply.Marshal(b, m, deterministic)
}
func (m *ChangePasswordReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordReply.Merge(m, src)
}
func (m *ChangePasswordReply) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordReply.Size(m)
}
func (m *ChangePasswordReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordReply.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordReply proto.InternalMessageInfo

type DeleteStreamRequest struct {
	Database             string   `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Stream               string   `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	ExpectedVersion      int64    `protobuf:"varint,3,opt,name=expectedVersion,proto3" json:"expectedVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStreamRequest) Reset()         { *m = DeleteStreamRequest{} }
func (m *DeleteStreamRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStreamRequest) ProtoMessage()    {}
func (*DeleteStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{2}
}

func (m *DeleteStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStreamRequest.Unmarshal(m, b)
}
func (m *DeleteStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStreamRequest.Marshal(b, m, deterministic)
}
func (m *DeleteStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStreamRequest.Merge(m, src)
}
func (m *DeleteStreamRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteStreamRequest.Size(m)
}
func (m *DeleteStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStreamRequest proto.InternalMessageInfo

func (m *DeleteStreamRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *DeleteStreamRequest) GetStream() string {
	if m != nil {
		return m.Stream
	}
	return ""
}

func (m *DeleteStreamRequest) GetExpectedVersion() int64 {
	if m != nil {
		return m.ExpectedVersion
	}
	return 0
}

type DeleteStreamReply struct {
	Version              int64    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStreamReply) Reset()         { *m = DeleteStreamReply{} }
func (m *DeleteStreamReply) String() string { return proto.CompactTextString(m) }
func (*DeleteStreamReply) ProtoMessage()    {}
func (*DeleteStreamReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{3}
}

func (m *DeleteStreamReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStreamReply.Unmarshal(m, b)
}
func (m *DeleteStreamReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStreamReply.Marshal(b, m, deterministic)
}
func (m *DeleteStreamReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStreamReply.Merge(m, src)
}
func (m *DeleteStreamReply) XXX_Size() int {
	return xxx_messageInfo_DeleteStreamReply.Size(m)
}
func (m *DeleteStreamReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStreamReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStreamReply proto.InternalMessageInfo

func (m *DeleteStreamReply) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type DeleteMessageRequest struct {
	Database             string   `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Stream               string   `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	Position             int64    `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMessageRequest) Reset()         { *m = DeleteMessageRequest{} }
func (m *DeleteMessageRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMessageRequest) ProtoMessage()    {}
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{4}
}

func (m *DeleteMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMessageRequest.Unmarshal(m, b)
}
func (m *DeleteMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMessageRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMessageRequest.Merge(m, src)
}
func (m *DeleteMessageRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMessageRequest.Size(m)
}
func (m *DeleteMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMessageRequest proto.InternalMessageInfo

func (m *DeleteMessageRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *DeleteMessageRequest) GetStream() string {
	if m != nil {
		return m.Stream
	}
	return ""
}

func (m *DeleteMessageRequest) GetPosition() int64 {
	if m != nil {
		return m.Position
	}
	return 0
}

type DeleteMessageReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMessageReply) Reset()         { *m = DeleteMessageReply{} }
func (m *DeleteMessageReply) String() string { return proto.CompactTextString(m) }
func (*DeleteMessageReply) ProtoMessage()    {}
func (*DeleteMessageReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{5}
}

func (m *DeleteMessageReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMessageReply.Unmarshal(m, b)
}
func (m *DeleteMessageReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMessageReply.Marshal(b, m, deterministic)
}
func (m *DeleteMessageReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMessageReply.Merge(m, src)
}
func (m *DeleteMessageReply) XXX_Size() int {
	return xxx_messageInfo_DeleteMessageReply.Size(m)
}
func (m *DeleteMessageReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMessageReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMessageReply proto.InternalMessageInfo

type ReadGlobalRequest struct {
	Database             string   `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Cursor               []byte   `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadGlobalRequest) Reset()         { *m = ReadGlobalRequest{} }
func (m *ReadGlobalRequest) String() string { return proto.CompactTextString(m) }
func (*ReadGlobalRequest) ProtoMessage()    {}
func (*ReadGlobalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{6}
}

func (m *ReadGlobalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadGlobalRequest.Unmarshal(m, b)
}
func (m *ReadGlobalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadGlobalRequest.Marshal(b, m, deterministic)
}
func (m *ReadGlobalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadGlobalRequest.Merge(m, src)
}
func (m *ReadGlobalRequest) XXX_Size() int {
	return xxx_messageInfo_ReadGlobalRequest.Size(m)
}
func (m *ReadGlobalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadGlobalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadGlobalRequest proto.InternalMessageInfo

func (m *ReadGlobalRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *ReadGlobalRequest) GetCursor() []byte {
	if m != nil {
		return m.Cursor
	}
	return nil
}

func (m *ReadGlobalRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ReadGlobalReply struct {
	Database             string     `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Cursor               []byte     `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Next                 []byte     `protobuf:"bytes,3,opt,name=next,proto3" json:"next,omitempty"`
	HasNext              bool       `protobuf:"varint,5,opt,name=hasNext,proto3" json:"hasNext,omitempty"`
	Messages             []*Message `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReadGlobalReply) Reset()         { *m = ReadGlobalReply{} }
func (m *ReadGlobalReply) String() string { return proto.CompactTextString(m) }
func (*ReadGlobalReply) ProtoMessage()    {}
func (*ReadGlobalReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{7}
}

func (m *ReadGlobalReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadGlobalReply.Unmarshal(m, b)
}
func (m *ReadGlobalReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadGlobalReply.Marshal(b, m, deterministic)
}
func (m *ReadGlobalReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadGlobalReply.Merge(m, src)
}
func (m *ReadGlobalReply) XXX_Size() int {
	return xxx_messageInfo_ReadGlobalReply.Size(m)
}
func (m *ReadGlobalReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadGlobalReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReadGlobalReply proto.InternalMessageInfo

func (m *ReadGlobalReply) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *ReadGlobalReply) GetCursor() []byte {
	if m != nil {
		return m.Cursor
	}
	return nil
}

func (m *ReadGlobalReply) GetNext() []byte {
	if m != nil {
		return m.Next
	}
	return nil
}

func (m *ReadGlobalReply) GetHasNext() bool {
	if m != nil {
		return m.HasNext
	}
	return false
}

func (m *ReadGlobalReply) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type GetStreamsRequest struct {
	Database             string   `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Cursor               string   `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Reverse              bool     `protobuf:"varint,3,opt,name=reverse,proto3" json:"reverse,omitempty"`
	Filter               string   `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	Limit                int32    `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStreamsRequest) Reset()         { *m = GetStreamsRequest{} }
func (m *GetStreamsRequest) String() string { return proto.CompactTextString(m) }
func (*GetStreamsRequest) ProtoMessage()    {}
func (*GetStreamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{8}
}

func (m *GetStreamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStreamsRequest.Unmarshal(m, b)
}
func (m *GetStreamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStreamsRequest.Marshal(b, m, deterministic)
}
func (m *GetStreamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStreamsRequest.Merge(m, src)
}
func (m *GetStreamsRequest) XXX_Size() int {
	return xxx_messageInfo_GetStreamsRequest.Size(m)
}
func (m *GetStreamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStreamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStreamsRequest proto.InternalMessageInfo

func (m *GetStreamsRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *GetStreamsRequest) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func (m *GetStreamsRequest) GetReverse() bool {
	if m != nil {
		return m.Reverse
	}
	return false
}

func (m *GetStreamsRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *GetStreamsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetStreamsReply struct {
	Total                int64    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Cursor               string   `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Reverse              bool     `protobuf:"varint,3,opt,name=reverse,proto3" json:"reverse,omitempty"`
	HasNext              bool     `protobuf:"varint,4,opt,name=hasNext,proto3" json:"hasNext,omitempty"`
	NextCursor           string   `protobuf:"bytes,5,opt,name=nextCursor,proto3" json:"nextCursor,omitempty"`
	Result               []string `protobuf:"bytes,6,rep,name=result,proto3" json:"result,omitempty"`
	Filter               string   `protobuf:"bytes,9,opt,name=filter,proto3" json:"filter,omitempty"`
	Limit                int32    `protobuf:"varint,10,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStreamsReply) Reset()         { *m = GetStreamsReply{} }
func (m *GetStreamsReply) String() string { return proto.CompactTextString(m) }
func (*GetStreamsReply) ProtoMessage()    {}
func (*GetStreamsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{9}
}

func (m *GetStreamsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStreamsReply.Unmarshal(m, b)
}
func (m *GetStreamsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStreamsReply.Marshal(b, m, deterministic)
}
func (m *GetStreamsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStreamsReply.Merge(m, src)
}
func (m *GetStreamsReply) XXX_Size() int {
	return xxx_messageInfo_GetStreamsReply.Size(m)
}
func (m *GetStreamsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStreamsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetStreamsReply proto.InternalMessageInfo

func (m *GetStreamsReply) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GetStreamsReply) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func (m *GetStreamsReply) GetReverse() bool {
	if m != nil {
		return m.Reverse
	}
	return false
}

func (m *GetStreamsReply) GetHasNext() bool {
	if m != nil {
		return m.HasNext
	}
	return false
}

func (m *GetStreamsReply) GetNextCursor() string {
	if m != nil {
		return m.NextCursor
	}
	return ""
}

func (m *GetStreamsReply) GetResult() []string {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetStreamsReply) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *GetStreamsReply) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{10}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReply) Reset()         { *m = PingReply{} }
func (m *PingReply) String() string { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()    {}
func (*PingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{11}
}

func (m *PingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReply.Unmarshal(m, b)
}
func (m *PingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReply.Marshal(b, m, deterministic)
}
func (m *PingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReply.Merge(m, src)
}
func (m *PingReply) XXX_Size() int {
	return xxx_messageInfo_PingReply.Size(m)
}
func (m *PingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReply.DiscardUnknown(m)
}

var xxx_messageInfo_PingReply proto.InternalMessageInfo

type GetDatabasesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDatabasesRequest) Reset()         { *m = GetDatabasesRequest{} }
func (m *GetDatabasesRequest) String() string { return proto.CompactTextString(m) }
func (*GetDatabasesRequest) ProtoMessage()    {}
func (*GetDatabasesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{12}
}

func (m *GetDatabasesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDatabasesRequest.Unmarshal(m, b)
}
func (m *GetDatabasesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDatabasesRequest.Marshal(b, m, deterministic)
}
func (m *GetDatabasesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDatabasesRequest.Merge(m, src)
}
func (m *GetDatabasesRequest) XXX_Size() int {
	return xxx_messageInfo_GetDatabasesRequest.Size(m)
}
func (m *GetDatabasesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDatabasesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDatabasesRequest proto.InternalMessageInfo

type GetDatabasesReply struct {
	Databases            []string `protobuf:"bytes,1,rep,name=databases,proto3" json:"databases,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDatabasesReply) Reset()         { *m = GetDatabasesReply{} }
func (m *GetDatabasesReply) String() string { return proto.CompactTextString(m) }
func (*GetDatabasesReply) ProtoMessage()    {}
func (*GetDatabasesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{13}
}

func (m *GetDatabasesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDatabasesReply.Unmarshal(m, b)
}
func (m *GetDatabasesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDatabasesReply.Marshal(b, m, deterministic)
}
func (m *GetDatabasesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDatabasesReply.Merge(m, src)
}
func (m *GetDatabasesReply) XXX_Size() int {
	return xxx_messageInfo_GetDatabasesReply.Size(m)
}
func (m *GetDatabasesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDatabasesReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetDatabasesReply proto.InternalMessageInfo

func (m *GetDatabasesReply) GetDatabases() []string {
	if m != nil {
		return m.Databases
	}
	return nil
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{14}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginReply struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{15}
}

func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (m *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(m, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

func (m *LoginReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type EnableAclRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableAclRequest) Reset()         { *m = EnableAclRequest{} }
func (m *EnableAclRequest) String() string { return proto.CompactTextString(m) }
func (*EnableAclRequest) ProtoMessage()    {}
func (*EnableAclRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{16}
}

func (m *EnableAclRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableAclRequest.Unmarshal(m, b)
}
func (m *EnableAclRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableAclRequest.Marshal(b, m, deterministic)
}
func (m *EnableAclRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableAclRequest.Merge(m, src)
}
func (m *EnableAclRequest) XXX_Size() int {
	return xxx_messageInfo_EnableAclRequest.Size(m)
}
func (m *EnableAclRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableAclRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnableAclRequest proto.InternalMessageInfo

func (m *EnableAclRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *EnableAclRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *EnableAclRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDatabaseRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDatabaseRequest) Reset()         { *m = GetDatabaseRequest{} }
func (m *GetDatabaseRequest) String() string { return proto.CompactTextString(m) }
func (*GetDatabaseRequest) ProtoMessage()    {}
func (*GetDatabaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{17}
}

func (m *GetDatabaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDatabaseRequest.Unmarshal(m, b)
}
func (m *GetDatabaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDatabaseRequest.Marshal(b, m, deterministic)
}
func (m *GetDatabaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDatabaseRequest.Merge(m, src)
}
func (m *GetDatabaseRequest) XXX_Size() int {
	return xxx_messageInfo_GetDatabaseRequest.Size(m)
}
func (m *GetDatabaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDatabaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDatabaseRequest proto.InternalMessageInfo

func (m *GetDatabaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetDatabaseReply struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDatabaseReply) Reset()         { *m = GetDatabaseReply{} }
func (m *GetDatabaseReply) String() string { return proto.CompactTextString(m) }
func (*GetDatabaseReply) ProtoMessage()    {}
func (*GetDatabaseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{18}
}

func (m *GetDatabaseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDatabaseReply.Unmarshal(m, b)
}
func (m *GetDatabaseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDatabaseReply.Marshal(b, m, deterministic)
}
func (m *GetDatabaseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDatabaseReply.Merge(m, src)
}
func (m *GetDatabaseReply) XXX_Size() int {
	return xxx_messageInfo_GetDatabaseReply.Size(m)
}
func (m *GetDatabaseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDatabaseReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetDatabaseReply proto.InternalMessageInfo

func (m *GetDatabaseReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type EnableAclReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableAclReply) Reset()         { *m = EnableAclReply{} }
func (m *EnableAclReply) String() string { return proto.CompactTextString(m) }
func (*EnableAclReply) ProtoMessage()    {}
func (*EnableAclReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{19}
}

func (m *EnableAclReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableAclReply.Unmarshal(m, b)
}
func (m *EnableAclReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableAclReply.Marshal(b, m, deterministic)
}
func (m *EnableAclReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableAclReply.Merge(m, src)
}
func (m *EnableAclReply) XXX_Size() int {
	return xxx_messageInfo_EnableAclReply.Size(m)
}
func (m *EnableAclReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableAclReply.DiscardUnknown(m)
}

var xxx_messageInfo_EnableAclReply proto.InternalMessageInfo

type GrandUserToDatabaseRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Database             string   `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrandUserToDatabaseRequest) Reset()         { *m = GrandUserToDatabaseRequest{} }
func (m *GrandUserToDatabaseRequest) String() string { return proto.CompactTextString(m) }
func (*GrandUserToDatabaseRequest) ProtoMessage()    {}
func (*GrandUserToDatabaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{20}
}

func (m *GrandUserToDatabaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrandUserToDatabaseRequest.Unmarshal(m, b)
}
func (m *GrandUserToDatabaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrandUserToDatabaseRequest.Marshal(b, m, deterministic)
}
func (m *GrandUserToDatabaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrandUserToDatabaseRequest.Merge(m, src)
}
func (m *GrandUserToDatabaseRequest) XXX_Size() int {
	return xxx_messageInfo_GrandUserToDatabaseRequest.Size(m)
}
func (m *GrandUserToDatabaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GrandUserToDatabaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GrandUserToDatabaseRequest proto.InternalMessageInfo

func (m *GrandUserToDatabaseRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GrandUserToDatabaseRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type GrandUserToDatabaseReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrandUserToDatabaseReply) Reset()         { *m = GrandUserToDatabaseReply{} }
func (m *GrandUserToDatabaseReply) String() string { return proto.CompactTextString(m) }
func (*GrandUserToDatabaseReply) ProtoMessage()    {}
func (*GrandUserToDatabaseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{21}
}

func (m *GrandUserToDatabaseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrandUserToDatabaseReply.Unmarshal(m, b)
}
func (m *GrandUserToDatabaseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrandUserToDatabaseReply.Marshal(b, m, deterministic)
}
func (m *GrandUserToDatabaseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrandUserToDatabaseReply.Merge(m, src)
}
func (m *GrandUserToDatabaseReply) XXX_Size() int {
	return xxx_messageInfo_GrandUserToDatabaseReply.Size(m)
}
func (m *GrandUserToDatabaseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GrandUserToDatabaseReply.DiscardUnknown(m)
}

var xxx_messageInfo_GrandUserToDatabaseReply proto.InternalMessageInfo

type CreateUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{22}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserReply) Reset()         { *m = CreateUserReply{} }
func (m *CreateUserReply) String() string { return proto.CompactTextString(m) }
func (*CreateUserReply) ProtoMessage()    {}
func (*CreateUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{23}
}

func (m *CreateUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserReply.Unmarshal(m, b)
}
func (m *CreateUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserReply.Marshal(b, m, deterministic)
}
func (m *CreateUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserReply.Merge(m, src)
}
func (m *CreateUserReply) XXX_Size() int {
	return xxx_messageInfo_CreateUserReply.Size(m)
}
func (m *CreateUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserReply proto.InternalMessageInfo

type CreateDatabaseRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDatabaseRequest) Reset()         { *m = CreateDatabaseRequest{} }
func (m *CreateDatabaseRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDatabaseRequest) ProtoMessage()    {}
func (*CreateDatabaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{24}
}

func (m *CreateDatabaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDatabaseRequest.Unmarshal(m, b)
}
func (m *CreateDatabaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDatabaseRequest.Marshal(b, m, deterministic)
}
func (m *CreateDatabaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDatabaseRequest.Merge(m, src)
}
func (m *CreateDatabaseRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDatabaseRequest.Size(m)
}
func (m *CreateDatabaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDatabaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDatabaseRequest proto.InternalMessageInfo

func (m *CreateDatabaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateDatabaseReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDatabaseReply) Reset()         { *m = CreateDatabaseReply{} }
func (m *CreateDatabaseReply) String() string { return proto.CompactTextString(m) }
func (*CreateDatabaseReply) ProtoMessage()    {}
func (*CreateDatabaseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{25}
}

func (m *CreateDatabaseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDatabaseReply.Unmarshal(m, b)
}
func (m *CreateDatabaseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDatabaseReply.Marshal(b, m, deterministic)
}
func (m *CreateDatabaseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDatabaseReply.Merge(m, src)
}
func (m *CreateDatabaseReply) XXX_Size() int {
	return xxx_messageInfo_CreateDatabaseReply.Size(m)
}
func (m *CreateDatabaseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDatabaseReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDatabaseReply proto.InternalMessageInfo

type SubscribeStreamRequest struct {
	Database             string   `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Stream               string   `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	From                 int64    `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	Count                uint32   `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeStreamRequest) Reset()         { *m = SubscribeStreamRequest{} }
func (m *SubscribeStreamRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeStreamRequest) ProtoMessage()    {}
func (*SubscribeStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{26}
}

func (m *SubscribeStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeStreamRequest.Unmarshal(m, b)
}
func (m *SubscribeStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeStreamRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeStreamRequest.Merge(m, src)
}
func (m *SubscribeStreamRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeStreamRequest.Size(m)
}
func (m *SubscribeStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeStreamRequest proto.InternalMessageInfo

func (m *SubscribeStreamRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *SubscribeStreamRequest) GetStream() string {
	if m != nil {
		return m.Stream
	}
	return ""
}

func (m *SubscribeStreamRequest) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *SubscribeStreamRequest) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// The request message containing the user's name.
type ReadStreamRequest struct {
	Database             string   `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Stream               string   `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	From                 int64    `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	Limit                uint32   `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Reverse              bool     `protobuf:"varint,5,opt,name=reverse,proto3" json:"reverse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadStreamRequest) Reset()         { *m = ReadStreamRequest{} }
func (m *ReadStreamRequest) String() string { return proto.CompactTextString(m) }
func (*ReadStreamRequest) ProtoMessage()    {}
func (*ReadStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{27}
}

func (m *ReadStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadStreamRequest.Unmarshal(m, b)
}
func (m *ReadStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadStreamRequest.Marshal(b, m, deterministic)
}
func (m *ReadStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadStreamRequest.Merge(m, src)
}
func (m *ReadStreamRequest) XXX_Size() int {
	return xxx_messageInfo_ReadStreamRequest.Size(m)
}
func (m *ReadStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadStreamRequest proto.InternalMessageInfo

func (m *ReadStreamRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *ReadStreamRequest) GetStream() string {
	if m != nil {
		return m.Stream
	}
	return ""
}

func (m *ReadStreamRequest) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *ReadStreamRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ReadStreamRequest) GetReverse() bool {
	if m != nil {
		return m.Reverse
	}
	return false
}

type Message struct {
	Stream               string           `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	Position             int64            `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	Type                 string           `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp            *types.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Header               []byte           `protobuf:"bytes,5,opt,name=header,proto3" json:"header,omitempty"`
	Value                []byte           `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{28}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetStream() string {
	if m != nil {
		return m.Stream
	}
	return ""
}

func (m *Message) GetPosition() int64 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *Message) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Message) GetTimestamp() *types.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Message) GetHeader() []byte {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Message) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Slice struct {
	Stream               string     `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	Version              int64      `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	From                 int64      `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	Count                int32      `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Next                 int64      `protobuf:"varint,5,opt,name=next,proto3" json:"next,omitempty"`
	HasNext              bool       `protobuf:"varint,6,opt,name=hasNext,proto3" json:"hasNext,omitempty"`
	Head                 int64      `protobuf:"varint,7,opt,name=head,proto3" json:"head,omitempty"`
	Messages             []*Message `protobuf:"bytes,8,rep,name=messages,proto3" json:"messages,omitempty"`
	Reverse              bool       `protobuf:"varint,9,opt,name=reverse,proto3" json:"reverse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Slice) Reset()         { *m = Slice{} }
func (m *Slice) String() string { return proto.CompactTextString(m) }
func (*Slice) ProtoMessage()    {}
func (*Slice) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{29}
}

func (m *Slice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Slice.Unmarshal(m, b)
}
func (m *Slice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Slice.Marshal(b, m, deterministic)
}
func (m *Slice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Slice.Merge(m, src)
}
func (m *Slice) XXX_Size() int {
	return xxx_messageInfo_Slice.Size(m)
}
func (m *Slice) XXX_DiscardUnknown() {
	xxx_messageInfo_Slice.DiscardUnknown(m)
}

var xxx_messageInfo_Slice proto.InternalMessageInfo

func (m *Slice) GetStream() string {
	if m != nil {
		return m.Stream
	}
	return ""
}

func (m *Slice) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Slice) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Slice) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Slice) GetNext() int64 {
	if m != nil {
		return m.Next
	}
	return 0
}

func (m *Slice) GetHasNext() bool {
	if m != nil {
		return m.HasNext
	}
	return false
}

func (m *Slice) GetHead() int64 {
	if m != nil {
		return m.Head
	}
	return 0
}

func (m *Slice) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *Slice) GetReverse() bool {
	if m != nil {
		return m.Reverse
	}
	return false
}

type MessageInput struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Header               []byte   `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	Value                []byte   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageInput) Reset()         { *m = MessageInput{} }
func (m *MessageInput) String() string { return proto.CompactTextString(m) }
func (*MessageInput) ProtoMessage()    {}
func (*MessageInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{30}
}

func (m *MessageInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageInput.Unmarshal(m, b)
}
func (m *MessageInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageInput.Marshal(b, m, deterministic)
}
func (m *MessageInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageInput.Merge(m, src)
}
func (m *MessageInput) XXX_Size() int {
	return xxx_messageInfo_MessageInput.Size(m)
}
func (m *MessageInput) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageInput.DiscardUnknown(m)
}

var xxx_messageInfo_MessageInput proto.InternalMessageInfo

func (m *MessageInput) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageInput) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MessageInput) GetHeader() []byte {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MessageInput) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type StreamInput struct {
	Database             string          `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Stream               string          `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	ExpectedVersion      int64           `protobuf:"varint,3,opt,name=expectedVersion,proto3" json:"expectedVersion,omitempty"`
	Messages             []*MessageInput `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StreamInput) Reset()         { *m = StreamInput{} }
func (m *StreamInput) String() string { return proto.CompactTextString(m) }
func (*StreamInput) ProtoMessage()    {}
func (*StreamInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{31}
}

func (m *StreamInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamInput.Unmarshal(m, b)
}
func (m *StreamInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamInput.Marshal(b, m, deterministic)
}
func (m *StreamInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamInput.Merge(m, src)
}
func (m *StreamInput) XXX_Size() int {
	return xxx_messageInfo_StreamInput.Size(m)
}
func (m *StreamInput) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamInput.DiscardUnknown(m)
}

var xxx_messageInfo_StreamInput proto.InternalMessageInfo

func (m *StreamInput) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *StreamInput) GetStream() string {
	if m != nil {
		return m.Stream
	}
	return ""
}

func (m *StreamInput) GetExpectedVersion() int64 {
	if m != nil {
		return m.ExpectedVersion
	}
	return 0
}

func (m *StreamInput) GetMessages() []*MessageInput {
	if m != nil {
		return m.Messages
	}
	return nil
}

type StreamAppendResult struct {
	Stream               string   `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	Version              int64    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Position             int64    `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	Head                 int64    `protobuf:"varint,4,opt,name=head,proto3" json:"head,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamAppendResult) Reset()         { *m = StreamAppendResult{} }
func (m *StreamAppendResult) String() string { return proto.CompactTextString(m) }
func (*StreamAppendResult) ProtoMessage()    {}
func (*StreamAppendResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{32}
}

func (m *StreamAppendResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamAppendResult.Unmarshal(m, b)
}
func (m *StreamAppendResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamAppendResult.Marshal(b, m, deterministic)
}
func (m *StreamAppendResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamAppendResult.Merge(m, src)
}
func (m *StreamAppendResult) XXX_Size() int {
	return xxx_messageInfo_StreamAppendResult.Size(m)
}
func (m *StreamAppendResult) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamAppendResult.DiscardUnknown(m)
}

var xxx_messageInfo_StreamAppendResult proto.InternalMessageInfo

func (m *StreamAppendResult) GetStream() string {
	if m != nil {
		return m.Stream
	}
	return ""
}

func (m *StreamAppendResult) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *StreamAppendResult) GetPosition() int64 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *StreamAppendResult) GetHead() int64 {
	if m != nil {
		return m.Head
	}
	return 0
}

type AppendStreamsRequest struct {
	Database             string         `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Inputs               []*StreamInput `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	IdempotencyKey       string         `protobuf:"bytes,3,opt,name=idempotencyKey,proto3" json:"idempotencyKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AppendStreamsRequest) Reset()         { *m = AppendStreamsRequest{} }
func (m *AppendStreamsRequest) String() string { return proto.CompactTextString(m) }
func (*AppendStreamsRequest) ProtoMessage()    {}
func (*AppendStreamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{33}
}

func (m *AppendStreamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendStreamsRequest.Unmarshal(m, b)
}
func (m *AppendStreamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendStreamsRequest.Marshal(b, m, deterministic)
}
func (m *AppendStreamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendStreamsRequest.Merge(m, src)
}
func (m *AppendStreamsRequest) XXX_Size() int {
	return xxx_messageInfo_AppendStreamsRequest.Size(m)
}
func (m *AppendStreamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendStreamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppendStreamsRequest proto.InternalMessageInfo

func (m *AppendStreamsRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *AppendStreamsRequest) GetInputs() []*StreamInput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *AppendStreamsRequest) GetIdempotencyKey() string {
	if m != nil {
		return m.IdempotencyKey
	}
	return ""
}

type AppendStreamsReply struct {
	Results              []*StreamAppendResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *AppendStreamsReply) Reset()         { *m = AppendStreamsReply{} }
func (m *AppendStreamsReply) String() string { return proto.CompactTextString(m) }
func (*AppendStreamsReply) ProtoMessage()    {}
func (*AppendStreamsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{34}
}

func (m *AppendStreamsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendStreamsReply.Unmarshal(m, b)
}
func (m *AppendStreamsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendStreamsReply.Marshal(b, m, deterministic)
}
func (m *AppendStreamsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendStreamsReply.Merge(m, src)
}
func (m *AppendStreamsReply) XXX_Size() int {
	return xxx_messageInfo_AppendStreamsReply.Size(m)
}
func (m *AppendStreamsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendStreamsReply.DiscardUnknown(m)
}

var xxx_messageInfo_AppendStreamsReply proto.InternalMessageInfo

func (m *AppendStreamsReply) GetResults() []*StreamAppendResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type AppendStreamRequest struct {
	Database             string          `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Stream               string          `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	Messages             []*MessageInput `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	ExpectedVersion      int64           `protobuf:"varint,4,opt,name=expectedVersion,proto3" json:"expectedVersion,omitempty"`
	IdempotencyKey       string          `protobuf:"bytes,5,opt,name=idempotencyKey,proto3" json:"idempotencyKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AppendStreamRequest) Reset()         { *m = AppendStreamRequest{} }
func (m *AppendStreamRequest) String() string { return proto.CompactTextString(m) }
func (*AppendStreamRequest) ProtoMessage()    {}
func (*AppendStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{35}
}

func (m *AppendStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendStreamRequest.Unmarshal(m, b)
}
func (m *AppendStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendStreamRequest.Marshal(b, m, deterministic)
}
func (m *AppendStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendStreamRequest.Merge(m, src)
}
func (m *AppendStreamRequest) XXX_Size() int {
	return xxx_messageInfo_AppendStreamRequest.Size(m)
}
func (m *AppendStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppendStreamRequest proto.InternalMessageInfo

func (m *AppendStreamRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *AppendStreamRequest) GetStream() string {
	if m != nil {
		return m.Stream
	}
	return ""
}

func (m *AppendStreamRequest) GetMessages() []*MessageInput {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *AppendStreamRequest) GetExpectedVersion() int64 {
	if m != nil {
		return m.ExpectedVersion
	}
	return 0
}

func (m *AppendStreamRequest) GetIdempotencyKey() string {
	if m != nil {
		return m.IdempotencyKey
	}
	return ""
}

func init() {
	proto.RegisterEnum("streamsdb.api.Direction", Direction_name, Direction_value)
	proto.RegisterType((*ChangePasswordRequest)(nil), "streamsdb.api.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordReply)(nil), "streamsdb.api.ChangePasswordReply")
	proto.RegisterType((*DeleteStreamRequest)(nil), "streamsdb.api.DeleteStreamRequest")
	proto.RegisterType((*DeleteStreamReply)(nil), "streamsdb.api.DeleteStreamReply")
	proto.RegisterType((*DeleteMessageRequest)(nil), "streamsdb.api.DeleteMessageRequest")
	proto.RegisterType((*DeleteMessageReply)(nil), "streamsdb.api.DeleteMessageReply")
	proto.RegisterType((*ReadGlobalRequest)(nil), "streamsdb.api.ReadGlobalRequest")
	proto.RegisterType((*ReadGlobalReply)(nil), "streamsdb.api.ReadGlobalReply")
	proto.RegisterType((*GetStreamsRequest)(nil), "streamsdb.api.GetStreamsRequest")
	proto.RegisterType((*GetStreamsReply)(nil), "streamsdb.api.GetStreamsReply")
	proto.RegisterType((*PingRequest)(nil), "streamsdb.api.PingRequest")
	proto.RegisterType((*PingReply)(nil), "streamsdb.api.PingReply")
	proto.RegisterType((*GetDatabasesRequest)(nil), "streamsdb.api.GetDatabasesRequest")
	proto.RegisterType((*GetDatabasesReply)(nil), "streamsdb.api.GetDatabasesReply")
	proto.RegisterType((*LoginRequest)(nil), "streamsdb.api.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "streamsdb.api.LoginReply")
	proto.RegisterType((*EnableAclRequest)(nil), "streamsdb.api.EnableAclRequest")
	proto.RegisterType((*GetDatabaseRequest)(nil), "streamsdb.api.GetDatabaseRequest")
	proto.RegisterType((*GetDatabaseReply)(nil), "streamsdb.api.GetDatabaseReply")
	proto.RegisterType((*EnableAclReply)(nil), "streamsdb.api.EnableAclReply")
	proto.RegisterType((*GrandUserToDatabaseRequest)(nil), "streamsdb.api.GrandUserToDatabaseRequest")
	proto.RegisterType((*GrandUserToDatabaseReply)(nil), "streamsdb.api.GrandUserToDatabaseReply")
	proto.RegisterType((*CreateUserRequest)(nil), "streamsdb.api.CreateUserRequest")
	proto.RegisterType((*CreateUserReply)(nil), "streamsdb.api.CreateUserReply")
	proto.RegisterType((*CreateDatabaseRequest)(nil), "streamsdb.api.CreateDatabaseRequest")
	proto.RegisterType((*CreateDatabaseReply)(nil), "streamsdb.api.CreateDatabaseReply")
	proto.RegisterType((*SubscribeStreamRequest)(nil), "streamsdb.api.SubscribeStreamRequest")
	proto.RegisterType((*ReadStreamRequest)(nil), "streamsdb.api.ReadStreamRequest")
	proto.RegisterType((*Message)(nil), "streamsdb.api.Message")
	proto.RegisterType((*Slice)(nil), "streamsdb.api.Slice")
	proto.RegisterType((*MessageInput)(nil), "streamsdb.api.MessageInput")
	proto.RegisterType((*StreamInput)(nil), "streamsdb.api.StreamInput")
	proto.RegisterType((*StreamAppendResult)(nil), "streamsdb.api.StreamAppendResult")
	proto.RegisterType((*AppendStreamsRequest)(nil), "streamsdb.api.AppendStreamsRequest")
	proto.RegisterType((*AppendStreamsReply)(nil), "streamsdb.api.AppendStreamsReply")
	proto.RegisterType((*AppendStreamRequest)(nil), "streamsdb.api.AppendStreamRequest")
}

func init() { proto.RegisterFile("api/api.proto", fileDescriptor_1b40cafcd4234784) }

var fileDescriptor_1b40cafcd4234784 = []byte{
	// 1361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xef, 0x6e, 0xe3, 0x44,
	0x10, 0x8f, 0x93, 0xb8, 0x4d, 0x26, 0x49, 0xff, 0x6c, 0xd3, 0xca, 0x18, 0xb8, 0xcb, 0x2d, 0x70,
	0x04, 0x10, 0x39, 0x08, 0x1f, 0x40, 0x42, 0x02, 0xf5, 0x5a, 0xae, 0x9c, 0x8e, 0xe3, 0x8a, 0x7b,
	0x5c, 0x05, 0x02, 0x89, 0x4d, 0xb2, 0x4d, 0xad, 0x73, 0x6c, 0xe3, 0x75, 0xca, 0xf5, 0x19, 0x90,
	0xe0, 0x25, 0x90, 0x90, 0x78, 0x03, 0xde, 0x83, 0x2f, 0x3c, 0x07, 0x9f, 0xf8, 0x86, 0x76, 0xd7,
	0x7f, 0xd6, 0x7f, 0x92, 0xb6, 0x57, 0xee, 0x9b, 0x67, 0x3d, 0xfe, 0xcd, 0xec, 0x6f, 0x66, 0x67,
	0x66, 0x0d, 0x1d, 0xe2, 0xdb, 0x77, 0x88, 0x6f, 0x0f, 0xfc, 0xc0, 0x0b, 0x3d, 0xd4, 0x61, 0x61,
	0x40, 0xc9, 0x8c, 0x4d, 0x46, 0x03, 0xe2, 0xdb, 0xe6, 0xcd, 0xa9, 0xe7, 0x4d, 0x1d, 0x7a, 0x47,
	0xbc, 0x1c, 0xcd, 0x4f, 0xee, 0x84, 0xf6, 0x8c, 0xb2, 0x90, 0xcc, 0x7c, 0xa9, 0x8f, 0x1f, 0xc1,
	0xf6, 0xde, 0x29, 0x71, 0xa7, 0xf4, 0x90, 0x30, 0xf6, 0x93, 0x17, 0x4c, 0x2c, 0xfa, 0xe3, 0x9c,
	0xb2, 0x10, 0x99, 0xd0, 0x98, 0x33, 0x1a, 0xb8, 0x64, 0x46, 0x0d, 0xad, 0xa7, 0xf5, 0x9b, 0x56,
	0x22, 0xf3, 0x77, 0x7e, 0xa4, 0x6e, 0x54, 0xe5, 0xbb, 0x58, 0xc6, 0xdb, 0xb0, 0x95, 0x07, 0xf4,
	0x9d, 0x73, 0xcc, 0x60, 0x6b, 0x9f, 0x3a, 0x34, 0xa4, 0x47, 0xc2, 0x3f, 0xc5, 0xca, 0x84, 0x84,
	0x64, 0x44, 0x58, 0x62, 0x25, 0x96, 0xd1, 0x0e, 0xac, 0xc8, 0xcd, 0x44, 0x36, 0x22, 0x09, 0xf5,
	0x61, 0x9d, 0x3e, 0xf3, 0xe9, 0x38, 0xa4, 0x93, 0x27, 0x34, 0x60, 0xb6, 0xe7, 0x1a, 0xb5, 0x9e,
	0xd6, 0xaf, 0x59, 0xf9, 0x65, 0xfc, 0x2e, 0x6c, 0x66, 0x8d, 0xfa, 0xce, 0x39, 0x32, 0x60, 0xf5,
	0x2c, 0xfa, 0x4c, 0x13, 0x9f, 0xc5, 0x22, 0x3e, 0x81, 0xae, 0x54, 0x7f, 0x48, 0x19, 0x23, 0x53,
	0x7a, 0x1d, 0x27, 0x39, 0x45, 0x1e, 0xb3, 0xc3, 0xd4, 0xbb, 0x44, 0xc6, 0x5d, 0x40, 0x39, 0x3b,
	0x9c, 0xa1, 0xef, 0x61, 0xd3, 0xa2, 0x64, 0x72, 0xe0, 0x78, 0x23, 0xe2, 0x5c, 0xd2, 0xf4, 0x78,
	0x1e, 0x30, 0x2f, 0x10, 0xa6, 0xdb, 0x56, 0x24, 0xa1, 0x2e, 0xe8, 0x8e, 0x3d, 0xb3, 0x43, 0x61,
	0x57, 0xb7, 0xa4, 0x80, 0x7f, 0xd7, 0x60, 0x5d, 0xc5, 0xe7, 0x54, 0x3c, 0x0f, 0x3a, 0x82, 0xba,
	0x4b, 0x9f, 0x49, 0xf0, 0xb6, 0x25, 0x9e, 0x39, 0xa5, 0xa7, 0x84, 0x7d, 0xc9, 0x97, 0xf5, 0x9e,
	0xd6, 0x6f, 0x58, 0xb1, 0x88, 0x86, 0xd0, 0x98, 0xc9, 0x4d, 0x32, 0xa3, 0xde, 0xab, 0xf5, 0x5b,
	0xc3, 0x9d, 0x41, 0x26, 0x43, 0x07, 0x31, 0x07, 0x89, 0x1e, 0xfe, 0x55, 0x83, 0xcd, 0x03, 0x1a,
	0xca, 0x98, 0xb1, 0xab, 0x33, 0xd1, 0x4c, 0x7c, 0x35, 0x60, 0x35, 0xa0, 0x3c, 0xba, 0x54, 0xb8,
	0xdb, 0xb0, 0x62, 0x91, 0x7f, 0x71, 0x62, 0x3b, 0x21, 0x0d, 0x8c, 0xba, 0xfc, 0x42, 0x4a, 0x29,
	0x77, 0xba, 0xca, 0xdd, 0xdf, 0x1a, 0xac, 0xab, 0x1e, 0x71, 0xee, 0xba, 0xa0, 0x87, 0x5e, 0x48,
	0x9c, 0x28, 0x89, 0xa4, 0xf0, 0x1c, 0x9e, 0x28, 0xdc, 0xd5, 0xb3, 0xdc, 0xdd, 0x00, 0xe0, 0xec,
	0xee, 0x49, 0x3c, 0x5d, 0xe0, 0x29, 0x2b, 0xdc, 0x56, 0x40, 0xd9, 0xdc, 0x09, 0x8d, 0x95, 0x5e,
	0x8d, 0xdb, 0x92, 0x92, 0xb2, 0xb7, 0x66, 0xf9, 0xde, 0x40, 0xdd, 0x5b, 0x07, 0x5a, 0x87, 0xb6,
	0x3b, 0x8d, 0x68, 0xc6, 0x2d, 0x68, 0x4a, 0x91, 0xa7, 0xe4, 0x36, 0x6c, 0x1d, 0xd0, 0x70, 0x3f,
	0xa2, 0x39, 0x0e, 0x05, 0x7e, 0x5f, 0xc4, 0x47, 0x59, 0xe6, 0x7c, 0xbc, 0x02, 0xcd, 0x38, 0x1e,
	0xcc, 0xd0, 0x84, 0x43, 0xe9, 0x02, 0xbe, 0x07, 0xed, 0x2f, 0xbc, 0xa9, 0xed, 0x5e, 0xb7, 0xba,
	0x60, 0x80, 0x08, 0x27, 0x89, 0xc1, 0x53, 0xea, 0x46, 0x10, 0x52, 0xc0, 0xa7, 0xb0, 0xf1, 0x99,
	0x4b, 0x46, 0x0e, 0xdd, 0x1d, 0x3b, 0xd7, 0xb4, 0xc7, 0x77, 0xc5, 0xec, 0xa9, 0x4b, 0xc2, 0x79,
	0x40, 0xa3, 0x94, 0x4f, 0x17, 0x70, 0x1f, 0x90, 0x42, 0x44, 0x6c, 0x8b, 0x9f, 0x90, 0xd4, 0x8e,
	0x78, 0xc6, 0xb7, 0x61, 0x23, 0xa3, 0xc9, 0xbd, 0x2f, 0xd3, 0xdb, 0x80, 0x35, 0xc5, 0x77, 0x1e,
	0x83, 0xc7, 0x60, 0x1e, 0x04, 0xc4, 0x9d, 0x7c, 0xcd, 0x68, 0xf0, 0xd8, 0xcb, 0xdb, 0xba, 0x60,
	0x5f, 0xc9, 0x89, 0xa9, 0x66, 0x4f, 0x0c, 0x36, 0xc1, 0x28, 0x45, 0xe5, 0x16, 0x1f, 0xc0, 0xe6,
	0x5e, 0x40, 0x49, 0x48, 0xf9, 0xcb, 0xeb, 0x06, 0x6c, 0x13, 0xd6, 0x55, 0x30, 0x8e, 0xff, 0x0e,
	0x6c, 0xcb, 0xa5, 0xcb, 0x10, 0xc7, 0xdb, 0x49, 0x4e, 0x99, 0x63, 0x9c, 0xc1, 0xce, 0xd1, 0x7c,
	0xc4, 0xc6, 0x81, 0x3d, 0xfa, 0x1f, 0x3a, 0x0a, 0x82, 0xfa, 0x49, 0xe0, 0xcd, 0xa2, 0x42, 0x2d,
	0x9e, 0x79, 0x6e, 0x8d, 0xbd, 0xb9, 0x2b, 0x4f, 0x65, 0xc7, 0x92, 0x02, 0xfe, 0x59, 0x93, 0x55,
	0xfa, 0x85, 0xd9, 0x94, 0x27, 0x34, 0xb2, 0x29, 0x04, 0xb5, 0x76, 0xe8, 0x99, 0xda, 0x81, 0xff,
	0xd4, 0x60, 0x35, 0xaa, 0x9f, 0x8a, 0x1d, 0x6d, 0x61, 0x23, 0xaa, 0x66, 0x1b, 0x11, 0xf7, 0x21,
	0x3c, 0xf7, 0x65, 0x62, 0x37, 0x2d, 0xf1, 0x8c, 0x3e, 0x82, 0x66, 0x32, 0x23, 0x08, 0x3f, 0x5a,
	0x43, 0x73, 0x20, 0xa7, 0x88, 0x41, 0x3c, 0x45, 0x0c, 0x1e, 0xc7, 0x1a, 0x56, 0xaa, 0xcc, 0x3d,
	0x38, 0xa5, 0x64, 0x42, 0x65, 0xad, 0x6a, 0x5b, 0x91, 0xc4, 0x77, 0x75, 0x46, 0x9c, 0x39, 0x35,
	0x56, 0xc4, 0xb2, 0x14, 0xf0, 0x3f, 0x1a, 0xe8, 0x47, 0x8e, 0x3d, 0x5e, 0xec, 0xb9, 0xd2, 0xa8,
	0xab, 0x99, 0x46, 0x7d, 0x71, 0xbc, 0xf4, 0x28, 0x5e, 0x49, 0xb7, 0xd2, 0xa5, 0x66, 0xbe, 0x5b,
	0xad, 0x64, 0x2b, 0x2e, 0x82, 0x3a, 0xf7, 0xd9, 0x58, 0x95, 0xda, 0xfc, 0x39, 0xd3, 0xc1, 0x1a,
	0x97, 0xeb, 0x60, 0x6a, 0xc4, 0x9a, 0xd9, 0x88, 0xfd, 0x00, 0xed, 0x48, 0xfd, 0xbe, 0xeb, 0xcf,
	0x43, 0xb4, 0x06, 0x55, 0x7b, 0x12, 0xed, 0xbb, 0x6a, 0x4f, 0x92, 0x88, 0x54, 0x95, 0x88, 0xa4,
	0xbc, 0xd6, 0xca, 0x79, 0xad, 0xab, 0xbc, 0xfe, 0xa6, 0x41, 0x4b, 0x66, 0xa7, 0xb4, 0xf0, 0x42,
	0x27, 0x2c, 0xf4, 0x61, 0xa1, 0xbf, 0xbf, 0x5c, 0xce, 0x8e, 0x70, 0x46, 0x69, 0xf2, 0x67, 0x80,
	0xa4, 0x97, 0xbb, 0xbe, 0x4f, 0xdd, 0x89, 0x95, 0xb4, 0xae, 0x2b, 0xa6, 0xc2, 0x92, 0x39, 0x2b,
	0x09, 0x67, 0x3d, 0x0d, 0x27, 0xfe, 0x45, 0x83, 0xae, 0x34, 0x79, 0x85, 0xf9, 0x62, 0x08, 0x2b,
	0x36, 0xf7, 0x9f, 0x19, 0x55, 0xb1, 0x47, 0x33, 0xb7, 0x47, 0x85, 0x6f, 0x2b, 0xd2, 0x44, 0xb7,
	0x61, 0xcd, 0x9e, 0xd0, 0x99, 0xef, 0x85, 0xd4, 0x1d, 0x9f, 0x3f, 0xa0, 0xe7, 0xd1, 0x29, 0xcb,
	0xad, 0xe2, 0xaf, 0x00, 0xe5, 0xfc, 0xe1, 0xbd, 0xe1, 0x63, 0x9e, 0x41, 0x9c, 0x12, 0xd9, 0x4b,
	0x5b, 0xc3, 0x5b, 0xa5, 0x26, 0x55, 0xf2, 0xac, 0xf8, 0x0b, 0xfc, 0x97, 0x06, 0x5b, 0x2a, 0xe6,
	0x75, 0xca, 0x94, 0x1a, 0xe0, 0xda, 0x15, 0x02, 0x5c, 0x96, 0x43, 0xf5, 0xf2, 0x1c, 0x2a, 0x32,
	0xa5, 0x97, 0x31, 0xf5, 0xf6, 0x6d, 0x68, 0xee, 0xdb, 0x01, 0x1d, 0x8b, 0xd8, 0xb6, 0x60, 0xf5,
	0xde, 0x23, 0xeb, 0x78, 0xd7, 0xda, 0xdf, 0xa8, 0xa0, 0x36, 0x34, 0xee, 0xee, 0xee, 0x3d, 0x10,
	0x92, 0x36, 0xfc, 0xb7, 0x05, 0xab, 0x11, 0x99, 0xe8, 0x09, 0xb4, 0xd5, 0x51, 0x05, 0xe1, 0x9c,
	0xf3, 0x25, 0xe3, 0x8d, 0xd9, 0x5b, 0xaa, 0xc3, 0xbb, 0x4f, 0x05, 0x1d, 0x41, 0x4b, 0x59, 0x46,
	0xb7, 0x16, 0x7f, 0x12, 0xa3, 0xde, 0x5c, 0xa6, 0x22, 0x41, 0x3f, 0x05, 0x5d, 0x0c, 0x37, 0x28,
	0x4f, 0xb1, 0x3a, 0x3a, 0x99, 0x2f, 0x95, 0xbf, 0xe4, 0x59, 0xf3, 0x10, 0x9a, 0xc9, 0xf4, 0x80,
	0xf2, 0x06, 0xf3, 0x33, 0x91, 0xf9, 0xea, 0x62, 0x05, 0xe9, 0xcf, 0x53, 0xd8, 0x2a, 0x19, 0x12,
	0xd0, 0x5b, 0xf9, 0x9d, 0x2c, 0x1c, 0x4f, 0xcc, 0x37, 0x2f, 0xa3, 0x2a, 0x8d, 0x1d, 0x02, 0xa4,
	0x83, 0x02, 0xca, 0xc7, 0xa0, 0x30, 0x90, 0x98, 0x37, 0x96, 0x68, 0x48, 0xc4, 0xef, 0x60, 0x2d,
	0x3b, 0x3a, 0xa0, 0xd7, 0x4b, 0xbf, 0xc9, 0x3b, 0x8d, 0x2f, 0xd0, 0x4a, 0xd1, 0x33, 0xf7, 0xdc,
	0x22, 0x7a, 0xd9, 0xbd, 0xba, 0x88, 0x5e, 0x72, 0x59, 0xae, 0xa0, 0x87, 0xd0, 0xb9, 0x1f, 0xd2,
	0x80, 0xc4, 0x57, 0xd7, 0x02, 0x21, 0x85, 0x21, 0xc4, 0x5c, 0xd0, 0x96, 0x70, 0xe5, 0x3d, 0x0d,
	0x7d, 0x0e, 0x90, 0x7e, 0x70, 0x09, 0xac, 0x6e, 0xbe, 0xda, 0xf0, 0x46, 0x2d, 0x90, 0x8e, 0xa1,
	0xad, 0x96, 0x96, 0xc2, 0x81, 0x2a, 0xa9, 0x3b, 0xe6, 0xc5, 0xb5, 0x0b, 0x57, 0xd0, 0x37, 0xd0,
	0xc9, 0xd4, 0x41, 0xf4, 0xda, 0x12, 0x64, 0xb6, 0x08, 0xba, 0x58, 0x4a, 0x25, 0x74, 0xe6, 0xbe,
	0x5d, 0x80, 0x2e, 0xbb, 0xf5, 0x17, 0xa0, 0x4b, 0xae, 0xec, 0x15, 0x5e, 0x5f, 0xd4, 0x3f, 0x0c,
	0x05, 0x3a, 0x4a, 0xfe, 0x79, 0x14, 0xea, 0x4b, 0xe1, 0x17, 0x05, 0xae, 0x20, 0x0b, 0xd6, 0x73,
	0xf3, 0x2d, 0x7a, 0x23, 0xcf, 0x62, 0xe9, 0xfc, 0xbb, 0x24, 0x74, 0x87, 0x32, 0x09, 0xe4, 0x0f,
	0x80, 0xd2, 0x24, 0xc8, 0xfc, 0x7b, 0x28, 0x9c, 0xb0, 0xdc, 0xdf, 0x03, 0x5c, 0x41, 0x9f, 0x40,
	0x9d, 0x5f, 0x16, 0x51, 0xbe, 0x1f, 0x2a, 0x17, 0x4a, 0xd3, 0x28, 0x7d, 0x97, 0x9c, 0xf9, 0xf4,
	0x5a, 0x8d, 0x4a, 0xea, 0x6e, 0x2e, 0xda, 0x37, 0x96, 0x68, 0x08, 0xc4, 0xbb, 0x3b, 0xdf, 0xd6,
	0x88, 0x6f, 0xff, 0x51, 0x5d, 0x8b, 0xd6, 0xf7, 0xef, 0x0e, 0x8e, 0xed, 0x80, 0x8e, 0x56, 0xc4,
	0xe8, 0xfa, 0xc1, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x99, 0x5b, 0x06, 0xf0, 0x2e, 0x13, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StreamsClient is the client API for Streams service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StreamsClient interface {
	GetDatabases(ctx context.Context, in *GetDatabasesRequest, opts ...grpc.CallOption) (*GetDatabasesReply, error)
	GetDatabase(ctx context.Context, in *GetDatabaseRequest, opts ...grpc.CallOption) (*GetDatabaseReply, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	EnableAcl(ctx context.Context, in *EnableAclRequest, opts ...grpc.CallOption) (*EnableAclReply, error)
	GrandUserToDatabase(ctx context.Context, in *GrandUserToDatabaseRequest, opts ...grpc.CallOption) (*GrandUserToDatabaseReply, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserReply, error)
	CreateDatabase(ctx context.Context, in *CreateDatabaseRequest, opts ...grpc.CallOption) (*CreateDatabaseReply, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordReply, error)
	IterateStream(ctx context.Context, in *ReadStreamRequest, opts ...grpc.CallOption) (Streams_IterateStreamClient, error)
	ReadStream(ctx context.Context, in *ReadStreamRequest, opts ...grpc.CallOption) (Streams_ReadStreamClient, error)
	AppendStream(ctx context.Context, in *AppendStreamRequest, opts ...grpc.CallOption) (*StreamAppendResult, error)
	AppendStreams(ctx context.Context, in *AppendStreamsRequest, opts ...grpc.CallOption) (*AppendStreamsReply, error)
	DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*DeleteMessageReply, error)
	DeleteStream(ctx context.Context, in *DeleteStreamRequest, opts ...grpc.CallOption) (*DeleteStreamReply, error)
	SubscribeStream(ctx context.Context, in *SubscribeStreamRequest, opts ...grpc.CallOption) (Streams_SubscribeStreamClient, error)
	ReadGlobal(ctx context.Context, in *ReadGlobalRequest, opts ...grpc.CallOption) (*ReadGlobalReply, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	GetStreams(ctx context.Context, in *GetStreamsRequest, opts ...grpc.CallOption) (*GetStreamsReply, error)
}

type streamsClient struct {
	cc *grpc.ClientConn
}

func NewStreamsClient(cc *grpc.ClientConn) StreamsClient {
	return &streamsClient{cc}
}

func (c *streamsClient) GetDatabases(ctx context.Context, in *GetDatabasesRequest, opts ...grpc.CallOption) (*GetDatabasesReply, error) {
	out := new(GetDatabasesReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/GetDatabases", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) GetDatabase(ctx context.Context, in *GetDatabaseRequest, opts ...grpc.CallOption) (*GetDatabaseReply, error) {
	out := new(GetDatabaseReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/GetDatabase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) EnableAcl(ctx context.Context, in *EnableAclRequest, opts ...grpc.CallOption) (*EnableAclReply, error) {
	out := new(EnableAclReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/EnableAcl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) GrandUserToDatabase(ctx context.Context, in *GrandUserToDatabaseRequest, opts ...grpc.CallOption) (*GrandUserToDatabaseReply, error) {
	out := new(GrandUserToDatabaseReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/GrandUserToDatabase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserReply, error) {
	out := new(CreateUserReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) CreateDatabase(ctx context.Context, in *CreateDatabaseRequest, opts ...grpc.CallOption) (*CreateDatabaseReply, error) {
	out := new(CreateDatabaseReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/CreateDatabase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordReply, error) {
	out := new(ChangePasswordReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) IterateStream(ctx context.Context, in *ReadStreamRequest, opts ...grpc.CallOption) (Streams_IterateStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Streams_serviceDesc.Streams[0], "/streamsdb.api.Streams/IterateStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamsIterateStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Streams_IterateStreamClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type streamsIterateStreamClient struct {
	grpc.ClientStream
}

func (x *streamsIterateStreamClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamsClient) ReadStream(ctx context.Context, in *ReadStreamRequest, opts ...grpc.CallOption) (Streams_ReadStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Streams_serviceDesc.Streams[1], "/streamsdb.api.Streams/ReadStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamsReadStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Streams_ReadStreamClient interface {
	Recv() (*Slice, error)
	grpc.ClientStream
}

type streamsReadStreamClient struct {
	grpc.ClientStream
}

func (x *streamsReadStreamClient) Recv() (*Slice, error) {
	m := new(Slice)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamsClient) AppendStream(ctx context.Context, in *AppendStreamRequest, opts ...grpc.CallOption) (*StreamAppendResult, error) {
	out := new(StreamAppendResult)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/AppendStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) AppendStreams(ctx context.Context, in *AppendStreamsRequest, opts ...grpc.CallOption) (*AppendStreamsReply, error) {
	out := new(AppendStreamsReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/AppendStreams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*DeleteMessageReply, error) {
	out := new(DeleteMessageReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/DeleteMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) DeleteStream(ctx context.Context, in *DeleteStreamRequest, opts ...grpc.CallOption) (*DeleteStreamReply, error) {
	out := new(DeleteStreamReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/DeleteStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) SubscribeStream(ctx context.Context, in *SubscribeStreamRequest, opts ...grpc.CallOption) (Streams_SubscribeStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Streams_serviceDesc.Streams[2], "/streamsdb.api.Streams/SubscribeStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamsSubscribeStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Streams_SubscribeStreamClient interface {
	Recv() (*Slice, error)
	grpc.ClientStream
}

type streamsSubscribeStreamClient struct {
	grpc.ClientStream
}

func (x *streamsSubscribeStreamClient) Recv() (*Slice, error) {
	m := new(Slice)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamsClient) ReadGlobal(ctx context.Context, in *ReadGlobalRequest, opts ...grpc.CallOption) (*ReadGlobalReply, error) {
	out := new(ReadGlobalReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/ReadGlobal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) GetStreams(ctx context.Context, in *GetStreamsRequest, opts ...grpc.CallOption) (*GetStreamsReply, error) {
	out := new(GetStreamsReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/GetStreams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamsServer is the server API for Streams service.
type StreamsServer interface {
	GetDatabases(context.Context, *GetDatabasesRequest) (*GetDatabasesReply, error)
	GetDatabase(context.Context, *GetDatabaseRequest) (*GetDatabaseReply, error)
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	EnableAcl(context.Context, *EnableAclRequest) (*EnableAclReply, error)
	GrandUserToDatabase(context.Context, *GrandUserToDatabaseRequest) (*GrandUserToDatabaseReply, error)
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserReply, error)
	CreateDatabase(context.Context, *CreateDatabaseRequest) (*CreateDatabaseReply, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordReply, error)
	IterateStream(*ReadStreamRequest, Streams_IterateStreamServer) error
	ReadStream(*ReadStreamRequest, Streams_ReadStreamServer) error
	AppendStream(context.Context, *AppendStreamRequest) (*StreamAppendResult, error)
	AppendStreams(context.Context, *AppendStreamsRequest) (*AppendStreamsReply, error)
	DeleteMessage(context.Context, *DeleteMessageRequest) (*DeleteMessageReply, error)
	DeleteStream(context.Context, *DeleteStreamRequest) (*DeleteStreamReply, error)
	SubscribeStream(*SubscribeStreamRequest, Streams_SubscribeStreamServer) error
	ReadGlobal(context.Context, *ReadGlobalRequest) (*ReadGlobalReply, error)
	Ping(context.Context, *PingRequest) (*PingReply, error)
	GetStreams(context.Context, *GetStreamsRequest) (*GetStreamsReply, error)
}

// UnimplementedStreamsServer can be embedded to have forward compatible implementations.
type UnimplementedStreamsServer struct {
}

func (*UnimplementedStreamsServer) GetDatabases(ctx context.Context, req *GetDatabasesRequest) (*GetDatabasesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDatabases not implemented")
}
func (*UnimplementedStreamsServer) GetDatabase(ctx context.Context, req *GetDatabaseRequest) (*GetDatabaseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDatabase not implemented")
}
func (*UnimplementedStreamsServer) Login(ctx context.Context, req *LoginRequest) (*LoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedStreamsServer) EnableAcl(ctx context.Context, req *EnableAclRequest) (*EnableAclReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableAcl not implemented")
}
func (*UnimplementedStreamsServer) GrandUserToDatabase(ctx context.Context, req *GrandUserToDatabaseRequest) (*GrandUserToDatabaseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrandUserToDatabase not implemented")
}
func (*UnimplementedStreamsServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedStreamsServer) CreateDatabase(ctx context.Context, req *CreateDatabaseRequest) (*CreateDatabaseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDatabase not implemented")
}
func (*UnimplementedStreamsServer) ChangePassword(ctx context.Context, req *ChangePasswordRequest) (*ChangePasswordReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (*UnimplementedStreamsServer) IterateStream(req *ReadStreamRequest, srv Streams_IterateStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method IterateStream not implemented")
}
func (*UnimplementedStreamsServer) ReadStream(req *ReadStreamRequest, srv Streams_ReadStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ReadStream not implemented")
}
func (*UnimplementedStreamsServer) AppendStream(ctx context.Context, req *AppendStreamRequest) (*StreamAppendResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendStream not implemented")
}
func (*UnimplementedStreamsServer) AppendStreams(ctx context.Context, req *AppendStreamsRequest) (*AppendStreamsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendStreams not implemented")
}
func (*UnimplementedStreamsServer) DeleteMessage(ctx context.Context, req *DeleteMessageRequest) (*DeleteMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (*UnimplementedStreamsServer) DeleteStream(ctx context.Context, req *DeleteStreamRequest) (*DeleteStreamReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStream not implemented")
}
func (*UnimplementedStreamsServer) SubscribeStream(req *SubscribeStreamRequest, srv Streams_SubscribeStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeStream not implemented")
}
func (*UnimplementedStreamsServer) ReadGlobal(ctx context.Context, req *ReadGlobalRequest) (*ReadGlobalReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadGlobal not implemented")
}
func (*UnimplementedStreamsServer) Ping(ctx context.Context, req *PingRequest) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedStreamsServer) GetStreams(ctx context.Context, req *GetStreamsRequest) (*GetStreamsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStreams not implemented")
}

func RegisterStreamsServer(s *grpc.Server, srv StreamsServer) {
	s.RegisterService(&_Streams_serviceDesc, srv)
}

func _Streams_GetDatabases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatabasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).GetDatabases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/GetDatabases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).GetDatabases(ctx, req.(*GetDatabasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_GetDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).GetDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/GetDatabase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).GetDatabase(ctx, req.(*GetDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_EnableAcl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableAclRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).EnableAcl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/EnableAcl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).EnableAcl(ctx, req.(*EnableAclRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_GrandUserToDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrandUserToDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).GrandUserToDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/GrandUserToDatabase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).GrandUserToDatabase(ctx, req.(*GrandUserToDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_CreateDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).CreateDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/CreateDatabase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).CreateDatabase(ctx, req.(*CreateDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_IterateStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamsServer).IterateStream(m, &streamsIterateStreamServer{stream})
}

type Streams_IterateStreamServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type streamsIterateStreamServer struct {
	grpc.ServerStream
}

func (x *streamsIterateStreamServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _Streams_ReadStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamsServer).ReadStream(m, &streamsReadStreamServer{stream})
}

type Streams_ReadStreamServer interface {
	Send(*Slice) error
	grpc.ServerStream
}

type streamsReadStreamServer struct {
	grpc.ServerStream
}

func (x *streamsReadStreamServer) Send(m *Slice) error {
	return x.ServerStream.SendMsg(m)
}

func _Streams_AppendStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).AppendStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/AppendStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).AppendStream(ctx, req.(*AppendStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_AppendStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).AppendStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/AppendStreams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).AppendStreams(ctx, req.(*AppendStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/DeleteMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).DeleteMessage(ctx, req.(*DeleteMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_DeleteStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).DeleteStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/DeleteStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).DeleteStream(ctx, req.(*DeleteStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_SubscribeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamsServer).SubscribeStream(m, &streamsSubscribeStreamServer{stream})
}

type Streams_SubscribeStreamServer interface {
	Send(*Slice) error
	grpc.ServerStream
}

type streamsSubscribeStreamServer struct {
	grpc.ServerStream
}

func (x *streamsSubscribeStreamServer) Send(m *Slice) error {
	return x.ServerStream.SendMsg(m)
}

func _Streams_ReadGlobal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadGlobalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).ReadGlobal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/ReadGlobal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).ReadGlobal(ctx, req.(*ReadGlobalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_GetStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).GetStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/GetStreams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).GetStreams(ctx, req.(*GetStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Streams_serviceDesc = grpc.ServiceDesc{
	ServiceName: "streamsdb.api.Streams",
	HandlerType: (*StreamsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDatabases",
			Handler:    _Streams_GetDatabases_Handler,
		},
		{
			MethodName: "GetDatabase",
			Handler:    _Streams_GetDatabase_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Streams_Login_Handler,
		},
		{
			MethodName: "EnableAcl",
			Handler:    _Streams_EnableAcl_Handler,
		},
		{
			MethodName: "GrandUserToDatabase",
			Handler:    _Streams_GrandUserToDatabase_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _Streams_CreateUser_Handler,
		},
		{
			MethodName: "CreateDatabase",
			Handler:    _Streams_CreateDatabase_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _Streams_ChangePassword_Handler,
		},
		{
			MethodName: "AppendStream",
			Handler:    _Streams_AppendStream_Handler,
		},
		{
			MethodName: "AppendStreams",
			Handler:    _Streams_AppendStreams_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _Streams_DeleteMessage_Handler,
		},
		{
			MethodName: "DeleteStream",
			Handler:    _Streams_DeleteStream_Handler,
		},
		{
			MethodName: "ReadGlobal",
			Handler:    _Streams_ReadGlobal_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Streams_Ping_Handler,
		},
		{
			MethodName: "GetStreams",
			Handler:    _Streams_GetStreams_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IterateStream",
			Handler:       _Streams_IterateStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReadStream",
			Handler:       _Streams_ReadStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeStream",
			Handler:       _Streams_SubscribeStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/api.proto",
}
