// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api.proto

package api

import (
	context "context"
	fmt "fmt"
	types "github.com/gogo/protobuf/types"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Direction int32

const (
	Direction_FORWARD  Direction = 0
	Direction_BACKWARD Direction = 1
)

var Direction_name = map[int32]string{
	0: "FORWARD",
	1: "BACKWARD",
}

var Direction_value = map[string]int32{
	"FORWARD":  0,
	"BACKWARD": 1,
}

func (x Direction) String() string {
	return proto.EnumName(Direction_name, int32(x))
}

func (Direction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{0}
}

type DeleteMessageRequest struct {
	Database             string   `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Stream               string   `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	Position             int64    `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMessageRequest) Reset()         { *m = DeleteMessageRequest{} }
func (m *DeleteMessageRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMessageRequest) ProtoMessage()    {}
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{0}
}

func (m *DeleteMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMessageRequest.Unmarshal(m, b)
}
func (m *DeleteMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMessageRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMessageRequest.Merge(m, src)
}
func (m *DeleteMessageRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMessageRequest.Size(m)
}
func (m *DeleteMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMessageRequest proto.InternalMessageInfo

func (m *DeleteMessageRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *DeleteMessageRequest) GetStream() string {
	if m != nil {
		return m.Stream
	}
	return ""
}

func (m *DeleteMessageRequest) GetPosition() int64 {
	if m != nil {
		return m.Position
	}
	return 0
}

type DeleteMessageReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMessageReply) Reset()         { *m = DeleteMessageReply{} }
func (m *DeleteMessageReply) String() string { return proto.CompactTextString(m) }
func (*DeleteMessageReply) ProtoMessage()    {}
func (*DeleteMessageReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{1}
}

func (m *DeleteMessageReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMessageReply.Unmarshal(m, b)
}
func (m *DeleteMessageReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMessageReply.Marshal(b, m, deterministic)
}
func (m *DeleteMessageReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMessageReply.Merge(m, src)
}
func (m *DeleteMessageReply) XXX_Size() int {
	return xxx_messageInfo_DeleteMessageReply.Size(m)
}
func (m *DeleteMessageReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMessageReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMessageReply proto.InternalMessageInfo

type ReadGlobalRequest struct {
	Database             string   `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	From                 []byte   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadGlobalRequest) Reset()         { *m = ReadGlobalRequest{} }
func (m *ReadGlobalRequest) String() string { return proto.CompactTextString(m) }
func (*ReadGlobalRequest) ProtoMessage()    {}
func (*ReadGlobalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{2}
}

func (m *ReadGlobalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadGlobalRequest.Unmarshal(m, b)
}
func (m *ReadGlobalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadGlobalRequest.Marshal(b, m, deterministic)
}
func (m *ReadGlobalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadGlobalRequest.Merge(m, src)
}
func (m *ReadGlobalRequest) XXX_Size() int {
	return xxx_messageInfo_ReadGlobalRequest.Size(m)
}
func (m *ReadGlobalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadGlobalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadGlobalRequest proto.InternalMessageInfo

func (m *ReadGlobalRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *ReadGlobalRequest) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *ReadGlobalRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ReadGlobalReply struct {
	Database             string   `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	From                 []byte   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Next                 []byte   `protobuf:"bytes,3,opt,name=next,proto3" json:"next,omitempty"`
	Values               []string `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadGlobalReply) Reset()         { *m = ReadGlobalReply{} }
func (m *ReadGlobalReply) String() string { return proto.CompactTextString(m) }
func (*ReadGlobalReply) ProtoMessage()    {}
func (*ReadGlobalReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{3}
}

func (m *ReadGlobalReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadGlobalReply.Unmarshal(m, b)
}
func (m *ReadGlobalReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadGlobalReply.Marshal(b, m, deterministic)
}
func (m *ReadGlobalReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadGlobalReply.Merge(m, src)
}
func (m *ReadGlobalReply) XXX_Size() int {
	return xxx_messageInfo_ReadGlobalReply.Size(m)
}
func (m *ReadGlobalReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadGlobalReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReadGlobalReply proto.InternalMessageInfo

func (m *ReadGlobalReply) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *ReadGlobalReply) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *ReadGlobalReply) GetNext() []byte {
	if m != nil {
		return m.Next
	}
	return nil
}

func (m *ReadGlobalReply) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type GetStreamsRequest struct {
	Database             string    `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Cursor               string    `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Direction            Direction `protobuf:"varint,3,opt,name=direction,proto3,enum=streamsdb.api.Direction" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetStreamsRequest) Reset()         { *m = GetStreamsRequest{} }
func (m *GetStreamsRequest) String() string { return proto.CompactTextString(m) }
func (*GetStreamsRequest) ProtoMessage()    {}
func (*GetStreamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{4}
}

func (m *GetStreamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStreamsRequest.Unmarshal(m, b)
}
func (m *GetStreamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStreamsRequest.Marshal(b, m, deterministic)
}
func (m *GetStreamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStreamsRequest.Merge(m, src)
}
func (m *GetStreamsRequest) XXX_Size() int {
	return xxx_messageInfo_GetStreamsRequest.Size(m)
}
func (m *GetStreamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStreamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStreamsRequest proto.InternalMessageInfo

func (m *GetStreamsRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *GetStreamsRequest) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func (m *GetStreamsRequest) GetDirection() Direction {
	if m != nil {
		return m.Direction
	}
	return Direction_FORWARD
}

type GetStreamsReply struct {
	Total                int64     `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Cursor               string    `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Direction            Direction `protobuf:"varint,3,opt,name=direction,proto3,enum=streamsdb.api.Direction" json:"direction,omitempty"`
	HasBefore            bool      `protobuf:"varint,4,opt,name=hasBefore,proto3" json:"hasBefore,omitempty"`
	HasAfter             bool      `protobuf:"varint,5,opt,name=hasAfter,proto3" json:"hasAfter,omitempty"`
	BeforeCursor         string    `protobuf:"bytes,6,opt,name=beforeCursor,proto3" json:"beforeCursor,omitempty"`
	AfterCursor          string    `protobuf:"bytes,7,opt,name=afterCursor,proto3" json:"afterCursor,omitempty"`
	Result               []string  `protobuf:"bytes,8,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetStreamsReply) Reset()         { *m = GetStreamsReply{} }
func (m *GetStreamsReply) String() string { return proto.CompactTextString(m) }
func (*GetStreamsReply) ProtoMessage()    {}
func (*GetStreamsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{5}
}

func (m *GetStreamsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStreamsReply.Unmarshal(m, b)
}
func (m *GetStreamsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStreamsReply.Marshal(b, m, deterministic)
}
func (m *GetStreamsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStreamsReply.Merge(m, src)
}
func (m *GetStreamsReply) XXX_Size() int {
	return xxx_messageInfo_GetStreamsReply.Size(m)
}
func (m *GetStreamsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStreamsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetStreamsReply proto.InternalMessageInfo

func (m *GetStreamsReply) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GetStreamsReply) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func (m *GetStreamsReply) GetDirection() Direction {
	if m != nil {
		return m.Direction
	}
	return Direction_FORWARD
}

func (m *GetStreamsReply) GetHasBefore() bool {
	if m != nil {
		return m.HasBefore
	}
	return false
}

func (m *GetStreamsReply) GetHasAfter() bool {
	if m != nil {
		return m.HasAfter
	}
	return false
}

func (m *GetStreamsReply) GetBeforeCursor() string {
	if m != nil {
		return m.BeforeCursor
	}
	return ""
}

func (m *GetStreamsReply) GetAfterCursor() string {
	if m != nil {
		return m.AfterCursor
	}
	return ""
}

func (m *GetStreamsReply) GetResult() []string {
	if m != nil {
		return m.Result
	}
	return nil
}

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{6}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReply) Reset()         { *m = PingReply{} }
func (m *PingReply) String() string { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()    {}
func (*PingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{7}
}

func (m *PingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReply.Unmarshal(m, b)
}
func (m *PingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReply.Marshal(b, m, deterministic)
}
func (m *PingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReply.Merge(m, src)
}
func (m *PingReply) XXX_Size() int {
	return xxx_messageInfo_PingReply.Size(m)
}
func (m *PingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReply.DiscardUnknown(m)
}

var xxx_messageInfo_PingReply proto.InternalMessageInfo

type GetDatabasesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDatabasesRequest) Reset()         { *m = GetDatabasesRequest{} }
func (m *GetDatabasesRequest) String() string { return proto.CompactTextString(m) }
func (*GetDatabasesRequest) ProtoMessage()    {}
func (*GetDatabasesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{8}
}

func (m *GetDatabasesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDatabasesRequest.Unmarshal(m, b)
}
func (m *GetDatabasesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDatabasesRequest.Marshal(b, m, deterministic)
}
func (m *GetDatabasesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDatabasesRequest.Merge(m, src)
}
func (m *GetDatabasesRequest) XXX_Size() int {
	return xxx_messageInfo_GetDatabasesRequest.Size(m)
}
func (m *GetDatabasesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDatabasesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDatabasesRequest proto.InternalMessageInfo

type GetDatabasesReply struct {
	Databases            []string `protobuf:"bytes,1,rep,name=databases,proto3" json:"databases,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDatabasesReply) Reset()         { *m = GetDatabasesReply{} }
func (m *GetDatabasesReply) String() string { return proto.CompactTextString(m) }
func (*GetDatabasesReply) ProtoMessage()    {}
func (*GetDatabasesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{9}
}

func (m *GetDatabasesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDatabasesReply.Unmarshal(m, b)
}
func (m *GetDatabasesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDatabasesReply.Marshal(b, m, deterministic)
}
func (m *GetDatabasesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDatabasesReply.Merge(m, src)
}
func (m *GetDatabasesReply) XXX_Size() int {
	return xxx_messageInfo_GetDatabasesReply.Size(m)
}
func (m *GetDatabasesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDatabasesReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetDatabasesReply proto.InternalMessageInfo

func (m *GetDatabasesReply) GetDatabases() []string {
	if m != nil {
		return m.Databases
	}
	return nil
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{10}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginReply struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{11}
}

func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (m *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(m, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

func (m *LoginReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type EnableAclRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableAclRequest) Reset()         { *m = EnableAclRequest{} }
func (m *EnableAclRequest) String() string { return proto.CompactTextString(m) }
func (*EnableAclRequest) ProtoMessage()    {}
func (*EnableAclRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{12}
}

func (m *EnableAclRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableAclRequest.Unmarshal(m, b)
}
func (m *EnableAclRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableAclRequest.Marshal(b, m, deterministic)
}
func (m *EnableAclRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableAclRequest.Merge(m, src)
}
func (m *EnableAclRequest) XXX_Size() int {
	return xxx_messageInfo_EnableAclRequest.Size(m)
}
func (m *EnableAclRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableAclRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnableAclRequest proto.InternalMessageInfo

func (m *EnableAclRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *EnableAclRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *EnableAclRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDatabaseRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDatabaseRequest) Reset()         { *m = GetDatabaseRequest{} }
func (m *GetDatabaseRequest) String() string { return proto.CompactTextString(m) }
func (*GetDatabaseRequest) ProtoMessage()    {}
func (*GetDatabaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{13}
}

func (m *GetDatabaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDatabaseRequest.Unmarshal(m, b)
}
func (m *GetDatabaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDatabaseRequest.Marshal(b, m, deterministic)
}
func (m *GetDatabaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDatabaseRequest.Merge(m, src)
}
func (m *GetDatabaseRequest) XXX_Size() int {
	return xxx_messageInfo_GetDatabaseRequest.Size(m)
}
func (m *GetDatabaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDatabaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDatabaseRequest proto.InternalMessageInfo

func (m *GetDatabaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetDatabaseReply struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDatabaseReply) Reset()         { *m = GetDatabaseReply{} }
func (m *GetDatabaseReply) String() string { return proto.CompactTextString(m) }
func (*GetDatabaseReply) ProtoMessage()    {}
func (*GetDatabaseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{14}
}

func (m *GetDatabaseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDatabaseReply.Unmarshal(m, b)
}
func (m *GetDatabaseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDatabaseReply.Marshal(b, m, deterministic)
}
func (m *GetDatabaseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDatabaseReply.Merge(m, src)
}
func (m *GetDatabaseReply) XXX_Size() int {
	return xxx_messageInfo_GetDatabaseReply.Size(m)
}
func (m *GetDatabaseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDatabaseReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetDatabaseReply proto.InternalMessageInfo

func (m *GetDatabaseReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type EnableAclReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableAclReply) Reset()         { *m = EnableAclReply{} }
func (m *EnableAclReply) String() string { return proto.CompactTextString(m) }
func (*EnableAclReply) ProtoMessage()    {}
func (*EnableAclReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{15}
}

func (m *EnableAclReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableAclReply.Unmarshal(m, b)
}
func (m *EnableAclReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableAclReply.Marshal(b, m, deterministic)
}
func (m *EnableAclReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableAclReply.Merge(m, src)
}
func (m *EnableAclReply) XXX_Size() int {
	return xxx_messageInfo_EnableAclReply.Size(m)
}
func (m *EnableAclReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableAclReply.DiscardUnknown(m)
}

var xxx_messageInfo_EnableAclReply proto.InternalMessageInfo

type GrandUserToDatabaseRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Database             string   `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrandUserToDatabaseRequest) Reset()         { *m = GrandUserToDatabaseRequest{} }
func (m *GrandUserToDatabaseRequest) String() string { return proto.CompactTextString(m) }
func (*GrandUserToDatabaseRequest) ProtoMessage()    {}
func (*GrandUserToDatabaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{16}
}

func (m *GrandUserToDatabaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrandUserToDatabaseRequest.Unmarshal(m, b)
}
func (m *GrandUserToDatabaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrandUserToDatabaseRequest.Marshal(b, m, deterministic)
}
func (m *GrandUserToDatabaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrandUserToDatabaseRequest.Merge(m, src)
}
func (m *GrandUserToDatabaseRequest) XXX_Size() int {
	return xxx_messageInfo_GrandUserToDatabaseRequest.Size(m)
}
func (m *GrandUserToDatabaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GrandUserToDatabaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GrandUserToDatabaseRequest proto.InternalMessageInfo

func (m *GrandUserToDatabaseRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GrandUserToDatabaseRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type GrandUserToDatabaseReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrandUserToDatabaseReply) Reset()         { *m = GrandUserToDatabaseReply{} }
func (m *GrandUserToDatabaseReply) String() string { return proto.CompactTextString(m) }
func (*GrandUserToDatabaseReply) ProtoMessage()    {}
func (*GrandUserToDatabaseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{17}
}

func (m *GrandUserToDatabaseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrandUserToDatabaseReply.Unmarshal(m, b)
}
func (m *GrandUserToDatabaseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrandUserToDatabaseReply.Marshal(b, m, deterministic)
}
func (m *GrandUserToDatabaseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrandUserToDatabaseReply.Merge(m, src)
}
func (m *GrandUserToDatabaseReply) XXX_Size() int {
	return xxx_messageInfo_GrandUserToDatabaseReply.Size(m)
}
func (m *GrandUserToDatabaseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GrandUserToDatabaseReply.DiscardUnknown(m)
}

var xxx_messageInfo_GrandUserToDatabaseReply proto.InternalMessageInfo

type CreateUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{18}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserReply) Reset()         { *m = CreateUserReply{} }
func (m *CreateUserReply) String() string { return proto.CompactTextString(m) }
func (*CreateUserReply) ProtoMessage()    {}
func (*CreateUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{19}
}

func (m *CreateUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserReply.Unmarshal(m, b)
}
func (m *CreateUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserReply.Marshal(b, m, deterministic)
}
func (m *CreateUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserReply.Merge(m, src)
}
func (m *CreateUserReply) XXX_Size() int {
	return xxx_messageInfo_CreateUserReply.Size(m)
}
func (m *CreateUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserReply proto.InternalMessageInfo

type CreateDatabaseRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDatabaseRequest) Reset()         { *m = CreateDatabaseRequest{} }
func (m *CreateDatabaseRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDatabaseRequest) ProtoMessage()    {}
func (*CreateDatabaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{20}
}

func (m *CreateDatabaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDatabaseRequest.Unmarshal(m, b)
}
func (m *CreateDatabaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDatabaseRequest.Marshal(b, m, deterministic)
}
func (m *CreateDatabaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDatabaseRequest.Merge(m, src)
}
func (m *CreateDatabaseRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDatabaseRequest.Size(m)
}
func (m *CreateDatabaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDatabaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDatabaseRequest proto.InternalMessageInfo

func (m *CreateDatabaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateDatabaseReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDatabaseReply) Reset()         { *m = CreateDatabaseReply{} }
func (m *CreateDatabaseReply) String() string { return proto.CompactTextString(m) }
func (*CreateDatabaseReply) ProtoMessage()    {}
func (*CreateDatabaseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{21}
}

func (m *CreateDatabaseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDatabaseReply.Unmarshal(m, b)
}
func (m *CreateDatabaseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDatabaseReply.Marshal(b, m, deterministic)
}
func (m *CreateDatabaseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDatabaseReply.Merge(m, src)
}
func (m *CreateDatabaseReply) XXX_Size() int {
	return xxx_messageInfo_CreateDatabaseReply.Size(m)
}
func (m *CreateDatabaseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDatabaseReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDatabaseReply proto.InternalMessageInfo

type SubscribeStreamRequest struct {
	Database             string   `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Stream               string   `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	From                 int64    `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	Count                uint32   `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeStreamRequest) Reset()         { *m = SubscribeStreamRequest{} }
func (m *SubscribeStreamRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeStreamRequest) ProtoMessage()    {}
func (*SubscribeStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{22}
}

func (m *SubscribeStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeStreamRequest.Unmarshal(m, b)
}
func (m *SubscribeStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeStreamRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeStreamRequest.Merge(m, src)
}
func (m *SubscribeStreamRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeStreamRequest.Size(m)
}
func (m *SubscribeStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeStreamRequest proto.InternalMessageInfo

func (m *SubscribeStreamRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *SubscribeStreamRequest) GetStream() string {
	if m != nil {
		return m.Stream
	}
	return ""
}

func (m *SubscribeStreamRequest) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *SubscribeStreamRequest) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// The request message containing the user's name.
type ReadStreamRequest struct {
	Database             string   `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Stream               string   `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	From                 int64    `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	Limit                uint32   `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadStreamRequest) Reset()         { *m = ReadStreamRequest{} }
func (m *ReadStreamRequest) String() string { return proto.CompactTextString(m) }
func (*ReadStreamRequest) ProtoMessage()    {}
func (*ReadStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{23}
}

func (m *ReadStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadStreamRequest.Unmarshal(m, b)
}
func (m *ReadStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadStreamRequest.Marshal(b, m, deterministic)
}
func (m *ReadStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadStreamRequest.Merge(m, src)
}
func (m *ReadStreamRequest) XXX_Size() int {
	return xxx_messageInfo_ReadStreamRequest.Size(m)
}
func (m *ReadStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadStreamRequest proto.InternalMessageInfo

func (m *ReadStreamRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *ReadStreamRequest) GetStream() string {
	if m != nil {
		return m.Stream
	}
	return ""
}

func (m *ReadStreamRequest) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *ReadStreamRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Message struct {
	Position             int64            `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	Type                 string           `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp            *types.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Header               []byte           `protobuf:"bytes,4,opt,name=header,proto3" json:"header,omitempty"`
	Value                []byte           `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{24}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetPosition() int64 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *Message) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Message) GetTimestamp() *types.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Message) GetHeader() []byte {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Message) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Slice struct {
	Stream               string     `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	From                 int64      `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	Count                int32      `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Next                 int64      `protobuf:"varint,4,opt,name=next,proto3" json:"next,omitempty"`
	HasNext              bool       `protobuf:"varint,5,opt,name=hasNext,proto3" json:"hasNext,omitempty"`
	Head                 int64      `protobuf:"varint,6,opt,name=head,proto3" json:"head,omitempty"`
	Messages             []*Message `protobuf:"bytes,7,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Slice) Reset()         { *m = Slice{} }
func (m *Slice) String() string { return proto.CompactTextString(m) }
func (*Slice) ProtoMessage()    {}
func (*Slice) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{25}
}

func (m *Slice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Slice.Unmarshal(m, b)
}
func (m *Slice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Slice.Marshal(b, m, deterministic)
}
func (m *Slice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Slice.Merge(m, src)
}
func (m *Slice) XXX_Size() int {
	return xxx_messageInfo_Slice.Size(m)
}
func (m *Slice) XXX_DiscardUnknown() {
	xxx_messageInfo_Slice.DiscardUnknown(m)
}

var xxx_messageInfo_Slice proto.InternalMessageInfo

func (m *Slice) GetStream() string {
	if m != nil {
		return m.Stream
	}
	return ""
}

func (m *Slice) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Slice) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Slice) GetNext() int64 {
	if m != nil {
		return m.Next
	}
	return 0
}

func (m *Slice) GetHasNext() bool {
	if m != nil {
		return m.HasNext
	}
	return false
}

func (m *Slice) GetHead() int64 {
	if m != nil {
		return m.Head
	}
	return 0
}

func (m *Slice) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type MessageInput struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Header               []byte   `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	Value                []byte   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageInput) Reset()         { *m = MessageInput{} }
func (m *MessageInput) String() string { return proto.CompactTextString(m) }
func (*MessageInput) ProtoMessage()    {}
func (*MessageInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{26}
}

func (m *MessageInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageInput.Unmarshal(m, b)
}
func (m *MessageInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageInput.Marshal(b, m, deterministic)
}
func (m *MessageInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageInput.Merge(m, src)
}
func (m *MessageInput) XXX_Size() int {
	return xxx_messageInfo_MessageInput.Size(m)
}
func (m *MessageInput) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageInput.DiscardUnknown(m)
}

var xxx_messageInfo_MessageInput proto.InternalMessageInfo

func (m *MessageInput) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageInput) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MessageInput) GetHeader() []byte {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MessageInput) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type AppendStreamRequest struct {
	Database             string          `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Stream               string          `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	Messages             []*MessageInput `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	ExpectedVersion      int64           `protobuf:"varint,4,opt,name=expectedVersion,proto3" json:"expectedVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AppendStreamRequest) Reset()         { *m = AppendStreamRequest{} }
func (m *AppendStreamRequest) String() string { return proto.CompactTextString(m) }
func (*AppendStreamRequest) ProtoMessage()    {}
func (*AppendStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{27}
}

func (m *AppendStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendStreamRequest.Unmarshal(m, b)
}
func (m *AppendStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendStreamRequest.Marshal(b, m, deterministic)
}
func (m *AppendStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendStreamRequest.Merge(m, src)
}
func (m *AppendStreamRequest) XXX_Size() int {
	return xxx_messageInfo_AppendStreamRequest.Size(m)
}
func (m *AppendStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppendStreamRequest proto.InternalMessageInfo

func (m *AppendStreamRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *AppendStreamRequest) GetStream() string {
	if m != nil {
		return m.Stream
	}
	return ""
}

func (m *AppendStreamRequest) GetMessages() []*MessageInput {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *AppendStreamRequest) GetExpectedVersion() int64 {
	if m != nil {
		return m.ExpectedVersion
	}
	return 0
}

type AppendStreamReply struct {
	From                 int64    `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendStreamReply) Reset()         { *m = AppendStreamReply{} }
func (m *AppendStreamReply) String() string { return proto.CompactTextString(m) }
func (*AppendStreamReply) ProtoMessage()    {}
func (*AppendStreamReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{28}
}

func (m *AppendStreamReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendStreamReply.Unmarshal(m, b)
}
func (m *AppendStreamReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendStreamReply.Marshal(b, m, deterministic)
}
func (m *AppendStreamReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendStreamReply.Merge(m, src)
}
func (m *AppendStreamReply) XXX_Size() int {
	return xxx_messageInfo_AppendStreamReply.Size(m)
}
func (m *AppendStreamReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendStreamReply.DiscardUnknown(m)
}

var xxx_messageInfo_AppendStreamReply proto.InternalMessageInfo

func (m *AppendStreamReply) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func init() {
	proto.RegisterEnum("streamsdb.api.Direction", Direction_name, Direction_value)
	proto.RegisterType((*DeleteMessageRequest)(nil), "streamsdb.api.DeleteMessageRequest")
	proto.RegisterType((*DeleteMessageReply)(nil), "streamsdb.api.DeleteMessageReply")
	proto.RegisterType((*ReadGlobalRequest)(nil), "streamsdb.api.ReadGlobalRequest")
	proto.RegisterType((*ReadGlobalReply)(nil), "streamsdb.api.ReadGlobalReply")
	proto.RegisterType((*GetStreamsRequest)(nil), "streamsdb.api.GetStreamsRequest")
	proto.RegisterType((*GetStreamsReply)(nil), "streamsdb.api.GetStreamsReply")
	proto.RegisterType((*PingRequest)(nil), "streamsdb.api.PingRequest")
	proto.RegisterType((*PingReply)(nil), "streamsdb.api.PingReply")
	proto.RegisterType((*GetDatabasesRequest)(nil), "streamsdb.api.GetDatabasesRequest")
	proto.RegisterType((*GetDatabasesReply)(nil), "streamsdb.api.GetDatabasesReply")
	proto.RegisterType((*LoginRequest)(nil), "streamsdb.api.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "streamsdb.api.LoginReply")
	proto.RegisterType((*EnableAclRequest)(nil), "streamsdb.api.EnableAclRequest")
	proto.RegisterType((*GetDatabaseRequest)(nil), "streamsdb.api.GetDatabaseRequest")
	proto.RegisterType((*GetDatabaseReply)(nil), "streamsdb.api.GetDatabaseReply")
	proto.RegisterType((*EnableAclReply)(nil), "streamsdb.api.EnableAclReply")
	proto.RegisterType((*GrandUserToDatabaseRequest)(nil), "streamsdb.api.GrandUserToDatabaseRequest")
	proto.RegisterType((*GrandUserToDatabaseReply)(nil), "streamsdb.api.GrandUserToDatabaseReply")
	proto.RegisterType((*CreateUserRequest)(nil), "streamsdb.api.CreateUserRequest")
	proto.RegisterType((*CreateUserReply)(nil), "streamsdb.api.CreateUserReply")
	proto.RegisterType((*CreateDatabaseRequest)(nil), "streamsdb.api.CreateDatabaseRequest")
	proto.RegisterType((*CreateDatabaseReply)(nil), "streamsdb.api.CreateDatabaseReply")
	proto.RegisterType((*SubscribeStreamRequest)(nil), "streamsdb.api.SubscribeStreamRequest")
	proto.RegisterType((*ReadStreamRequest)(nil), "streamsdb.api.ReadStreamRequest")
	proto.RegisterType((*Message)(nil), "streamsdb.api.Message")
	proto.RegisterType((*Slice)(nil), "streamsdb.api.Slice")
	proto.RegisterType((*MessageInput)(nil), "streamsdb.api.MessageInput")
	proto.RegisterType((*AppendStreamRequest)(nil), "streamsdb.api.AppendStreamRequest")
	proto.RegisterType((*AppendStreamReply)(nil), "streamsdb.api.AppendStreamReply")
}

func init() { proto.RegisterFile("api/api.proto", fileDescriptor_1b40cafcd4234784) }

var fileDescriptor_1b40cafcd4234784 = []byte{
	// 1140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0xb6, 0xfc, 0x13, 0xc7, 0xc7, 0x4e, 0x1c, 0x6f, 0x9c, 0x8c, 0x10, 0x85, 0xba, 0x0b, 0xb4,
	0x06, 0x66, 0x1c, 0x30, 0x33, 0xc0, 0x15, 0x8c, 0x13, 0x93, 0x0c, 0x53, 0x0a, 0x1d, 0x25, 0xb4,
	0x53, 0x86, 0x0b, 0xd6, 0xd6, 0xda, 0xd6, 0x54, 0x96, 0x54, 0xed, 0xaa, 0x34, 0x57, 0x3c, 0x02,
	0x77, 0xdc, 0x73, 0xcb, 0xf0, 0x0e, 0xbc, 0x1a, 0xb3, 0xbb, 0xfa, 0xb7, 0x92, 0x86, 0x49, 0xb9,
	0xd3, 0x39, 0xfb, 0xe9, 0xfc, 0xee, 0x9e, 0x6f, 0x17, 0x76, 0x88, 0x6f, 0x1f, 0x11, 0xdf, 0x1e,
	0xf9, 0x81, 0xc7, 0x3d, 0xb4, 0xc3, 0x78, 0x40, 0xc9, 0x9a, 0x59, 0xb3, 0x11, 0xf1, 0x6d, 0xe3,
	0xee, 0xd2, 0xf3, 0x96, 0x0e, 0x3d, 0x92, 0x8b, 0xb3, 0x70, 0x71, 0xc4, 0xed, 0x35, 0x65, 0x9c,
	0xac, 0x7d, 0x85, 0xc7, 0x0b, 0xe8, 0x4f, 0xa9, 0x43, 0x39, 0x7d, 0x44, 0x19, 0x23, 0x4b, 0x6a,
	0xd2, 0x17, 0x21, 0x65, 0x1c, 0x19, 0xb0, 0x6d, 0x11, 0x4e, 0x66, 0x84, 0x51, 0x5d, 0x1b, 0x68,
	0xc3, 0x96, 0x99, 0xc8, 0xe8, 0x10, 0xb6, 0x94, 0x17, 0xbd, 0x2a, 0x57, 0x22, 0x49, 0xfc, 0xe3,
	0x7b, 0xcc, 0xe6, 0xb6, 0xe7, 0xea, 0xb5, 0x81, 0x36, 0xac, 0x99, 0x89, 0x8c, 0xfb, 0x80, 0x0a,
	0x7e, 0x7c, 0xe7, 0x12, 0x3f, 0x83, 0x9e, 0x49, 0x89, 0x75, 0xe6, 0x78, 0x33, 0xe2, 0xdc, 0xc4,
	0x35, 0x82, 0xfa, 0x22, 0xf0, 0x94, 0xe3, 0x8e, 0x29, 0xbf, 0x51, 0x1f, 0x1a, 0x8e, 0xbd, 0xb6,
	0xb9, 0xf4, 0xd9, 0x30, 0x95, 0x80, 0xd7, 0xd0, 0xcd, 0x9a, 0xf6, 0x9d, 0xcb, 0xff, 0x6c, 0x18,
	0x41, 0xdd, 0xa5, 0xaf, 0x94, 0xdd, 0x8e, 0x29, 0xbf, 0x45, 0xee, 0x2f, 0x89, 0x13, 0x52, 0xa6,
	0xd7, 0x07, 0x35, 0x91, 0xbb, 0x92, 0xf0, 0x6f, 0xd0, 0x3b, 0xa3, 0xfc, 0x5c, 0x15, 0xff, 0x86,
	0x45, 0x9c, 0x87, 0x01, 0xf3, 0x82, 0xb8, 0x88, 0x4a, 0x42, 0x9f, 0x43, 0xcb, 0xb2, 0x03, 0x3a,
	0x4f, 0xaa, 0xb8, 0x3b, 0xd6, 0x47, 0xb9, 0xa6, 0x8e, 0xa6, 0xf1, 0xba, 0x99, 0x42, 0xf1, 0xef,
	0x55, 0xe8, 0x66, 0x23, 0x10, 0x09, 0xf7, 0xa1, 0xc1, 0x3d, 0x4e, 0x1c, 0xe9, 0xbc, 0x66, 0x2a,
	0xe1, 0x4d, 0x7b, 0x46, 0x77, 0xa0, 0xb5, 0x22, 0xec, 0x98, 0x2e, 0xbc, 0x80, 0xea, 0xf5, 0x81,
	0x36, 0xdc, 0x36, 0x53, 0x85, 0xa8, 0xc1, 0x8a, 0xb0, 0xc9, 0x82, 0xd3, 0x40, 0x6f, 0xc8, 0xc5,
	0x44, 0x46, 0x18, 0x3a, 0x33, 0x89, 0x3a, 0x51, 0xf1, 0x6c, 0xc9, 0x78, 0x72, 0x3a, 0x34, 0x80,
	0x36, 0x11, 0xe0, 0x08, 0xd2, 0x94, 0x90, 0xac, 0x4a, 0xe4, 0x13, 0x50, 0x16, 0x3a, 0x5c, 0xdf,
	0x56, 0x2d, 0x51, 0x12, 0xde, 0x81, 0xf6, 0x63, 0xdb, 0x5d, 0x46, 0xcd, 0xc0, 0x6d, 0x68, 0x29,
	0x51, 0x6c, 0xbc, 0x03, 0xd8, 0x3f, 0xa3, 0x7c, 0x1a, 0x35, 0x23, 0x6e, 0x18, 0xfe, 0x54, 0x76,
	0x31, 0xa3, 0x16, 0x55, 0xbc, 0x03, 0xad, 0xb8, 0x6b, 0x4c, 0xd7, 0xa4, 0x8b, 0x54, 0x81, 0x4f,
	0xa1, 0xf3, 0x9d, 0xb7, 0xb4, 0xdd, 0x4c, 0xcf, 0x43, 0x46, 0x03, 0x97, 0xac, 0x93, 0x9e, 0xc7,
	0xb2, 0x3c, 0x20, 0x84, 0xb1, 0x5f, 0xbd, 0xc0, 0x8a, 0x6a, 0x9f, 0xc8, 0x18, 0x03, 0x44, 0x76,
	0x92, 0xce, 0x3d, 0xa7, 0x6e, 0x64, 0x42, 0x09, 0x78, 0x05, 0x7b, 0xdf, 0xb8, 0x64, 0xe6, 0xd0,
	0xc9, 0xdc, 0xb9, 0xa5, 0x3f, 0x91, 0x15, 0xb3, 0x97, 0x2e, 0xe1, 0x61, 0x40, 0xa3, 0x1d, 0x9e,
	0x2a, 0xf0, 0x10, 0x50, 0xa6, 0x10, 0xb1, 0x2f, 0x71, 0x20, 0x52, 0x3f, 0xf2, 0x1b, 0xdf, 0x87,
	0xbd, 0x1c, 0x52, 0x44, 0x5f, 0x86, 0xdb, 0x83, 0xdd, 0x4c, 0xec, 0xa2, 0x07, 0x17, 0x60, 0x9c,
	0x05, 0xc4, 0xb5, 0x7e, 0x64, 0x34, 0xb8, 0xf0, 0x8a, 0xbe, 0x5e, 0x93, 0x57, 0x72, 0xae, 0xaa,
	0xf9, 0x73, 0x85, 0x0d, 0xd0, 0x4b, 0xad, 0x0a, 0x8f, 0x0f, 0xa1, 0x77, 0x12, 0x50, 0xc2, 0xa9,
	0x58, 0xbc, 0x6d, 0xc3, 0x7a, 0xd0, 0xcd, 0x1a, 0x13, 0xf6, 0x3f, 0x86, 0x03, 0xa5, 0xba, 0x49,
	0xe1, 0x0e, 0x60, 0xbf, 0x08, 0x16, 0x36, 0x5e, 0xc2, 0xe1, 0x79, 0x38, 0x63, 0xf3, 0xc0, 0x9e,
	0x51, 0x75, 0x98, 0x6f, 0x33, 0x92, 0xe3, 0xb1, 0xa6, 0xc6, 0x71, 0x32, 0x2f, 0xe7, 0x5e, 0xe8,
	0x72, 0x79, 0x56, 0x77, 0x4c, 0x25, 0xe0, 0x17, 0x6a, 0x14, 0xff, 0x6f, 0x2e, 0xd5, 0x88, 0x8e,
	0x5c, 0xaa, 0x11, 0xfd, 0xa7, 0x06, 0xcd, 0x88, 0x0e, 0x72, 0xdc, 0xa1, 0xe5, 0xb9, 0x43, 0x58,
	0xe4, 0x97, 0x7e, 0xdc, 0x6a, 0xf9, 0x8d, 0xbe, 0x84, 0x56, 0x42, 0x65, 0xd2, 0x55, 0x7b, 0x6c,
	0x8c, 0x14, 0xd9, 0x8d, 0x62, 0xb2, 0x1b, 0x5d, 0xc4, 0x08, 0x33, 0x05, 0x8b, 0xb8, 0x57, 0x94,
	0x58, 0x34, 0x90, 0xc1, 0x74, 0xcc, 0x48, 0x12, 0x31, 0xca, 0x59, 0x2e, 0xa7, 0x54, 0xc7, 0x54,
	0x02, 0xfe, 0x47, 0x83, 0xc6, 0xb9, 0x63, 0xcf, 0xb3, 0xf9, 0x6a, 0xa5, 0xf9, 0x56, 0xcb, 0x4a,
	0x1c, 0x51, 0x92, 0x14, 0x12, 0x3e, 0xa9, 0x2b, 0xa4, 0xe4, 0x13, 0x1d, 0x9a, 0x2b, 0xc2, 0xbe,
	0x17, 0x6a, 0x35, 0x1d, 0x63, 0x51, 0xa0, 0x45, 0x64, 0x72, 0x28, 0xd6, 0x4c, 0xf9, 0x8d, 0xc6,
	0xb0, 0xbd, 0x56, 0x05, 0x63, 0x7a, 0x73, 0x50, 0x1b, 0xb6, 0xc7, 0x87, 0x85, 0x09, 0x1d, 0xd3,
	0x6b, 0x82, 0xc3, 0xbf, 0x40, 0x27, 0x52, 0x7e, 0xeb, 0xfa, 0x21, 0x47, 0xbb, 0x50, 0xb5, 0xad,
	0x28, 0x87, 0xaa, 0x6d, 0x95, 0x56, 0x37, 0xad, 0x51, 0xad, 0xbc, 0x46, 0xf5, 0x6c, 0x8d, 0xfe,
	0xd6, 0x60, 0x7f, 0xe2, 0xfb, 0xd4, 0x7d, 0x03, 0xbb, 0xe7, 0x8b, 0x4c, 0x86, 0x35, 0x99, 0xe1,
	0xdb, 0xe5, 0x19, 0xca, 0x64, 0xd2, 0x34, 0xd1, 0x10, 0xba, 0xf4, 0x95, 0x4f, 0xe7, 0x9c, 0x5a,
	0x4f, 0x68, 0xc0, 0xc4, 0x3e, 0x52, 0x75, 0x2e, 0xaa, 0xf1, 0x03, 0xe8, 0xe5, 0xa3, 0x8d, 0x46,
	0x96, 0xec, 0xa2, 0x96, 0x76, 0xf1, 0xa3, 0xfb, 0xd0, 0x4a, 0x08, 0x0f, 0xb5, 0xa1, 0x79, 0xfa,
	0x83, 0xf9, 0x74, 0x62, 0x4e, 0xf7, 0x2a, 0xa8, 0x03, 0xdb, 0xc7, 0x93, 0x93, 0x87, 0x52, 0xd2,
	0xc6, 0x7f, 0xb4, 0xa0, 0x19, 0xf1, 0x2e, 0x7a, 0x02, 0x9d, 0x2c, 0x83, 0x20, 0x5c, 0x88, 0xbe,
	0x84, 0x75, 0x8c, 0xc1, 0xb5, 0x18, 0x31, 0x14, 0x2a, 0xe8, 0x1c, 0xda, 0x19, 0x35, 0xba, 0x77,
	0xf5, 0x2f, 0xb1, 0xd5, 0xbb, 0xd7, 0x41, 0x94, 0xd1, 0xaf, 0xa1, 0x21, 0x39, 0x07, 0x15, 0x6b,
	0x9c, 0x65, 0x34, 0xe3, 0xad, 0xf2, 0x45, 0x51, 0xb5, 0x47, 0xd0, 0x4a, 0x86, 0x3a, 0x2a, 0x3a,
	0x2c, 0x52, 0x95, 0xf1, 0xce, 0xd5, 0x00, 0x15, 0xcf, 0x73, 0xd8, 0x2f, 0x99, 0xdd, 0xe8, 0xc3,
	0x62, 0x26, 0x57, 0xb2, 0x86, 0xf1, 0xe0, 0x26, 0x50, 0xe5, 0xec, 0x31, 0x40, 0x3a, 0xbf, 0x51,
	0xb1, 0x07, 0x1b, 0x3c, 0x61, 0xbc, 0x7b, 0x0d, 0x42, 0x59, 0xfc, 0x19, 0x76, 0xf3, 0x13, 0x1d,
	0xbd, 0x5f, 0xfa, 0x4f, 0x31, 0x68, 0xfc, 0x1a, 0x94, 0xb2, 0x7e, 0x0a, 0x90, 0x0e, 0xe8, 0x8d,
	0x78, 0x37, 0x66, 0xb7, 0xd1, 0x2f, 0x20, 0xe4, 0x14, 0xc3, 0x15, 0xb1, 0x43, 0xb3, 0xdb, 0x7f,
	0x63, 0x87, 0x96, 0x9c, 0xe4, 0x8d, 0x1d, 0xba, 0x71, 0x7e, 0x70, 0x05, 0x3d, 0x83, 0x9d, 0xdc,
	0x0d, 0x1f, 0xbd, 0x57, 0xbc, 0x3c, 0x96, 0xbc, 0x33, 0x8c, 0x7b, 0xd7, 0x83, 0x94, 0x69, 0x13,
	0xba, 0x05, 0x4e, 0x44, 0x1f, 0x14, 0xb3, 0x2b, 0xe5, 0xcc, 0xab, 0x8a, 0xf0, 0x89, 0x26, 0xda,
	0x9f, 0xbe, 0x0f, 0x4a, 0xcb, 0x99, 0x7b, 0x95, 0x6c, 0xb4, 0xbf, 0xf0, 0xb8, 0xc0, 0x15, 0xf4,
	0x15, 0xd4, 0xc5, 0x05, 0x13, 0x19, 0x05, 0x64, 0xe6, 0x12, 0x6a, 0xe8, 0xa5, 0x6b, 0xc9, 0x86,
	0x4c, 0x2f, 0xf0, 0xa8, 0x64, 0x28, 0xe4, 0x5f, 0x17, 0x1b, 0x11, 0x15, 0x6e, 0xff, 0xb8, 0x72,
	0x7c, 0xf8, 0x53, 0x8d, 0xf8, 0xf6, 0x5f, 0xd5, 0xdd, 0x48, 0x3f, 0x3d, 0x1e, 0x3d, 0xb5, 0x03,
	0x3a, 0xdb, 0x92, 0x0c, 0xf9, 0xd9, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x67, 0x2a, 0x6d, 0x16,
	0x3c, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StreamsClient is the client API for Streams service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StreamsClient interface {
	GetDatabases(ctx context.Context, in *GetDatabasesRequest, opts ...grpc.CallOption) (*GetDatabasesReply, error)
	GetDatabase(ctx context.Context, in *GetDatabaseRequest, opts ...grpc.CallOption) (*GetDatabaseReply, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	EnableAcl(ctx context.Context, in *EnableAclRequest, opts ...grpc.CallOption) (*EnableAclReply, error)
	GrandUserToDatabase(ctx context.Context, in *GrandUserToDatabaseRequest, opts ...grpc.CallOption) (*GrandUserToDatabaseReply, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserReply, error)
	CreateDatabase(ctx context.Context, in *CreateDatabaseRequest, opts ...grpc.CallOption) (*CreateDatabaseReply, error)
	ReadStream(ctx context.Context, in *ReadStreamRequest, opts ...grpc.CallOption) (*Slice, error)
	AppendStream(ctx context.Context, in *AppendStreamRequest, opts ...grpc.CallOption) (*AppendStreamReply, error)
	DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*DeleteMessageReply, error)
	SubscribeStream(ctx context.Context, in *SubscribeStreamRequest, opts ...grpc.CallOption) (Streams_SubscribeStreamClient, error)
	ReadGlobal(ctx context.Context, in *ReadGlobalRequest, opts ...grpc.CallOption) (*ReadGlobalReply, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	GetStreams(ctx context.Context, in *GetStreamsRequest, opts ...grpc.CallOption) (*GetStreamsReply, error)
}

type streamsClient struct {
	cc *grpc.ClientConn
}

func NewStreamsClient(cc *grpc.ClientConn) StreamsClient {
	return &streamsClient{cc}
}

func (c *streamsClient) GetDatabases(ctx context.Context, in *GetDatabasesRequest, opts ...grpc.CallOption) (*GetDatabasesReply, error) {
	out := new(GetDatabasesReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/GetDatabases", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) GetDatabase(ctx context.Context, in *GetDatabaseRequest, opts ...grpc.CallOption) (*GetDatabaseReply, error) {
	out := new(GetDatabaseReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/GetDatabase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) EnableAcl(ctx context.Context, in *EnableAclRequest, opts ...grpc.CallOption) (*EnableAclReply, error) {
	out := new(EnableAclReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/EnableAcl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) GrandUserToDatabase(ctx context.Context, in *GrandUserToDatabaseRequest, opts ...grpc.CallOption) (*GrandUserToDatabaseReply, error) {
	out := new(GrandUserToDatabaseReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/GrandUserToDatabase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserReply, error) {
	out := new(CreateUserReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) CreateDatabase(ctx context.Context, in *CreateDatabaseRequest, opts ...grpc.CallOption) (*CreateDatabaseReply, error) {
	out := new(CreateDatabaseReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/CreateDatabase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) ReadStream(ctx context.Context, in *ReadStreamRequest, opts ...grpc.CallOption) (*Slice, error) {
	out := new(Slice)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/ReadStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) AppendStream(ctx context.Context, in *AppendStreamRequest, opts ...grpc.CallOption) (*AppendStreamReply, error) {
	out := new(AppendStreamReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/AppendStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*DeleteMessageReply, error) {
	out := new(DeleteMessageReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/DeleteMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) SubscribeStream(ctx context.Context, in *SubscribeStreamRequest, opts ...grpc.CallOption) (Streams_SubscribeStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Streams_serviceDesc.Streams[0], "/streamsdb.api.Streams/SubscribeStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamsSubscribeStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Streams_SubscribeStreamClient interface {
	Recv() (*Slice, error)
	grpc.ClientStream
}

type streamsSubscribeStreamClient struct {
	grpc.ClientStream
}

func (x *streamsSubscribeStreamClient) Recv() (*Slice, error) {
	m := new(Slice)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamsClient) ReadGlobal(ctx context.Context, in *ReadGlobalRequest, opts ...grpc.CallOption) (*ReadGlobalReply, error) {
	out := new(ReadGlobalReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/ReadGlobal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamsClient) GetStreams(ctx context.Context, in *GetStreamsRequest, opts ...grpc.CallOption) (*GetStreamsReply, error) {
	out := new(GetStreamsReply)
	err := c.cc.Invoke(ctx, "/streamsdb.api.Streams/GetStreams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamsServer is the server API for Streams service.
type StreamsServer interface {
	GetDatabases(context.Context, *GetDatabasesRequest) (*GetDatabasesReply, error)
	GetDatabase(context.Context, *GetDatabaseRequest) (*GetDatabaseReply, error)
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	EnableAcl(context.Context, *EnableAclRequest) (*EnableAclReply, error)
	GrandUserToDatabase(context.Context, *GrandUserToDatabaseRequest) (*GrandUserToDatabaseReply, error)
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserReply, error)
	CreateDatabase(context.Context, *CreateDatabaseRequest) (*CreateDatabaseReply, error)
	ReadStream(context.Context, *ReadStreamRequest) (*Slice, error)
	AppendStream(context.Context, *AppendStreamRequest) (*AppendStreamReply, error)
	DeleteMessage(context.Context, *DeleteMessageRequest) (*DeleteMessageReply, error)
	SubscribeStream(*SubscribeStreamRequest, Streams_SubscribeStreamServer) error
	ReadGlobal(context.Context, *ReadGlobalRequest) (*ReadGlobalReply, error)
	Ping(context.Context, *PingRequest) (*PingReply, error)
	GetStreams(context.Context, *GetStreamsRequest) (*GetStreamsReply, error)
}

// UnimplementedStreamsServer can be embedded to have forward compatible implementations.
type UnimplementedStreamsServer struct {
}

func (*UnimplementedStreamsServer) GetDatabases(ctx context.Context, req *GetDatabasesRequest) (*GetDatabasesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDatabases not implemented")
}
func (*UnimplementedStreamsServer) GetDatabase(ctx context.Context, req *GetDatabaseRequest) (*GetDatabaseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDatabase not implemented")
}
func (*UnimplementedStreamsServer) Login(ctx context.Context, req *LoginRequest) (*LoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedStreamsServer) EnableAcl(ctx context.Context, req *EnableAclRequest) (*EnableAclReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableAcl not implemented")
}
func (*UnimplementedStreamsServer) GrandUserToDatabase(ctx context.Context, req *GrandUserToDatabaseRequest) (*GrandUserToDatabaseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrandUserToDatabase not implemented")
}
func (*UnimplementedStreamsServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedStreamsServer) CreateDatabase(ctx context.Context, req *CreateDatabaseRequest) (*CreateDatabaseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDatabase not implemented")
}
func (*UnimplementedStreamsServer) ReadStream(ctx context.Context, req *ReadStreamRequest) (*Slice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadStream not implemented")
}
func (*UnimplementedStreamsServer) AppendStream(ctx context.Context, req *AppendStreamRequest) (*AppendStreamReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendStream not implemented")
}
func (*UnimplementedStreamsServer) DeleteMessage(ctx context.Context, req *DeleteMessageRequest) (*DeleteMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (*UnimplementedStreamsServer) SubscribeStream(req *SubscribeStreamRequest, srv Streams_SubscribeStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeStream not implemented")
}
func (*UnimplementedStreamsServer) ReadGlobal(ctx context.Context, req *ReadGlobalRequest) (*ReadGlobalReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadGlobal not implemented")
}
func (*UnimplementedStreamsServer) Ping(ctx context.Context, req *PingRequest) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedStreamsServer) GetStreams(ctx context.Context, req *GetStreamsRequest) (*GetStreamsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStreams not implemented")
}

func RegisterStreamsServer(s *grpc.Server, srv StreamsServer) {
	s.RegisterService(&_Streams_serviceDesc, srv)
}

func _Streams_GetDatabases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatabasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).GetDatabases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/GetDatabases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).GetDatabases(ctx, req.(*GetDatabasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_GetDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).GetDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/GetDatabase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).GetDatabase(ctx, req.(*GetDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_EnableAcl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableAclRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).EnableAcl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/EnableAcl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).EnableAcl(ctx, req.(*EnableAclRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_GrandUserToDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrandUserToDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).GrandUserToDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/GrandUserToDatabase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).GrandUserToDatabase(ctx, req.(*GrandUserToDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_CreateDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).CreateDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/CreateDatabase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).CreateDatabase(ctx, req.(*CreateDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_ReadStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).ReadStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/ReadStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).ReadStream(ctx, req.(*ReadStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_AppendStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).AppendStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/AppendStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).AppendStream(ctx, req.(*AppendStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/DeleteMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).DeleteMessage(ctx, req.(*DeleteMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_SubscribeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamsServer).SubscribeStream(m, &streamsSubscribeStreamServer{stream})
}

type Streams_SubscribeStreamServer interface {
	Send(*Slice) error
	grpc.ServerStream
}

type streamsSubscribeStreamServer struct {
	grpc.ServerStream
}

func (x *streamsSubscribeStreamServer) Send(m *Slice) error {
	return x.ServerStream.SendMsg(m)
}

func _Streams_ReadGlobal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadGlobalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).ReadGlobal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/ReadGlobal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).ReadGlobal(ctx, req.(*ReadGlobalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streams_GetStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamsServer).GetStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamsdb.api.Streams/GetStreams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamsServer).GetStreams(ctx, req.(*GetStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Streams_serviceDesc = grpc.ServiceDesc{
	ServiceName: "streamsdb.api.Streams",
	HandlerType: (*StreamsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDatabases",
			Handler:    _Streams_GetDatabases_Handler,
		},
		{
			MethodName: "GetDatabase",
			Handler:    _Streams_GetDatabase_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Streams_Login_Handler,
		},
		{
			MethodName: "EnableAcl",
			Handler:    _Streams_EnableAcl_Handler,
		},
		{
			MethodName: "GrandUserToDatabase",
			Handler:    _Streams_GrandUserToDatabase_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _Streams_CreateUser_Handler,
		},
		{
			MethodName: "CreateDatabase",
			Handler:    _Streams_CreateDatabase_Handler,
		},
		{
			MethodName: "ReadStream",
			Handler:    _Streams_ReadStream_Handler,
		},
		{
			MethodName: "AppendStream",
			Handler:    _Streams_AppendStream_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _Streams_DeleteMessage_Handler,
		},
		{
			MethodName: "ReadGlobal",
			Handler:    _Streams_ReadGlobal_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Streams_Ping_Handler,
		},
		{
			MethodName: "GetStreams",
			Handler:    _Streams_GetStreams_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeStream",
			Handler:       _Streams_SubscribeStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/api.proto",
}
